### ISSUE TITLE
<podcast:email> Is it really necessary?

### ISSUE THREAD

**Issue by dellagustin** [Podcastindex-org/podcast-namespace#10]
RSS 2.0 already has the channel level elements `managingEditor` and `webMaster`.

`webMaster` is defines as:

> Email address for person responsible for technical issues relating to channel.

It seems suitable or the current purpose described for `<podcast:email>`:

> This is a channel-level element. An email address that can be used to verify ownership of this feed during move and import operations. This could be a public email or a virtual email address at the hosting provider that redirects to the owner's true email address.

I don't have a strong opinion on which should take priority, `managingEditor` and `webMaster`.

Source: https://www.rssboard.org/rss-specification

**Comment by daveajones** [comment]
I agree with the redundancy here, but I feels it's necessary in this particular case.  Existing emails in feeds are going to be all over the map with regards to accuracy.  This feels like a perfect time (during namespace implementation) to say that this element is the one tied to transfer locking contact, so people know that it's _has_ to be valid and can't be a junk address.

The one thing I'm open to here is possibly renaming it to something like podcast:contactEmail or something like that.

**Comment by theDanielJLewis** [comment]
I think you could expand this to support additional email types, and you might want to consider the "type" approach. For example:

`<podcast:email type="contact">`
`<podcast:email type="advertising">`
`<podcast:email type="verification">`

Then, if `type` is missing, it will be assumed the default contact email for everything.

**Comment by daveajones** [comment]
I like this a lot.  Having it fallback to everything in case of no attribute is a great approach.

**Comment by theDanielJLewis** [comment]
There could also be a recommended fallback order for developers. Kind of like how summaries/descriptions "work" in many apps. (For example, Google Podcasts uses descriptions in this order: `<googleplay:description>` ➜ `<itunes:summary>` ➜ `<description>`.)

**Comment by daveajones** [comment]
Yes that is good too.  I do similar things as well across the parser.

How about the following:  We keep a separate tag for verification and just rename it to:

`<podcast:ownerVerification>[email address]</podcast:ownerVerification>`

That tag is so critically important that I think having it stand alone and be unambiguous, with no attribute requirements is best.

And, that allows for changing your idea to something even more flexible, like this:

```
<podcast:contact type="feedback" method="link">[link to a forum or chat room]</podcast:contact>
<podcast:contact type="advertising" method="email">[email address]</podcast:contact>
<podcast:contact type="abuse" method="email">[email address for DMCA takedowns, etc.]</podcast:contact>
```

So, there can be different contact methods for each of the areas of concern.

**Comment by Lehmancreations** [comment]
I like the podcast:contact type="" 

one question is this an open ended tag so you could add what ever. say type="livestream" method="link" or is it limited to predefined types?

**Comment by theDanielJLewis** [comment]
I like the `method` approach since that can help better point people to the right place.

**Comment by daveajones** [comment]
@Lehmancreations Something like that would be better to use alternateEnclosure tag.

**Comment by dellagustin** [comment]
> Yes that is good too. I do similar things as well across the parser.
> 
> How about the following: We keep a separate tag for verification and just rename it to:
> 
> `<podcast:ownerVerification>[email address]</podcast:ownerVerification>`
> 
> That tag is so critically important that I think having it stand alone and be unambiguous, with no attribute requirements is best.
This looks great to me, gives it a clear unambiguous purpose.

> And, that allows for changing your idea to something even more flexible, like this:
> 
> ```
> <podcast:contact type="feedback" method="link">[link to a forum or chat room]</podcast:contact>
> <podcast:contact type="advertising" method="email">[email address]</podcast:contact>
> <podcast:contact type="abuse" method="email">[email address for DMCA takedowns, etc.]</podcast:contact>
> ```
> 
> So, there can be different contact methods for each of the areas of concern.
No strong feelings here. I see a minor overlap with #14 (contact vs social media information), but it is hard to tell.
