### ISSUE TITLE
Proposal: non-integer episode numbers

### ISSUE THREAD

**Issue by coldacid** [Podcastindex-org/podcast-namespace#101]
Something that appears to still be missing in podcast RSS feeds in general is a simple, standardized way of stating the episode number for a particular podcast episode. I'd like to propose the addition of `<podcast:episodeNumber>` to the namespace, as follows:

## Episode Number
`<podcast:episodeNumber>`

#### Parent
`<item>`

#### Content
The display value to show for the episode number. If no value is provided for content, the podcast application SHOULD display the episode number (lead by the season number if present) as is appropriate for the user's locale.

#### Attributes
 - **episode:** Number of the podcast episode within the specified season, or for the show as a whole if **season** has no value. Required.

 - **season:** Number of the show season to which the episode belongs. Optional.

#### Examples
`<podcast:episodeNumber episode="16" />`

`<podcast:episodeNumber season="3" episode="1">S3E1</podcast:episodeNumber>`

`<podcast:episodeNumber episode="200.1">Special Episode</podcast:episodeNumber>`

#### Notes
Episode numbers MUST be unique for the pair of (season,episode) values in the tag. Where the season attribute is not set, it should be assumed to be 0 for this purpose. (Multiple episodes may have the same episode attribute value, but must have different season attribute values.)

Episode ordering based on episode numbers should order based on season (assuming the value of 0 if the season attribute has no value) with episodes in the same season ordered by episode number.

Episode numbers MAY be decimal values, to allow for special episodes outside of regular episode numbering.

**Comment by theDanielJLewis** [comment]
Why this instead of the Apple Podcasts spec?

**Comment by coldacid** [comment]
@theDanielJLewis to be honest, I didn't see this in their spec. Oops.

**Comment by coldacid** [comment]
With the `<podcast:season>` proposal, we could adapt this for non-integer episode numbers in a similar style to #108 by swapping the tag content and the `episode` attribute, and scratching the `season` attribute altogether.

**Comment by coldacid** [comment]
Rewritten to focus solely on episode number, predicated on design of the `<podcast:season>` tag suggested in #108:

----

## Episode Number
`<podcast:episode display="[display value of episode number (string)]">[(int|decimal)]</podcast:episode>`

#### Parent
`<item>`

#### Content
The episode number itself, as an integer or decimal value.

#### Attributes
 - **display:** The value to display as episode number, if different from the actual episode number. Optional.

#### Examples
`<podcast:episode>16</podcast:episode>`

`<podcast:episode display="S3E1">1</podcast:episode>`

`<podcast:episode display="Special Episode">200.1</podcast:episode>`

#### Notes
Episode numbers MUST be unique for the pair of (season,episode) tags in the item. Where the `<podcast:season>` tag is not set, it should be assumed to be 0 for this purpose. (Multiple episodes may have the same episode attribute value, but must have different season attribute values.)

Episode ordering based on episode numbers should order based on season (assuming the value of 0 if the `<podcast:season>` tag has no value) with episodes in the same season ordered by episode number.
