### ISSUE TITLE
ChapterJson: Add regions

### ISSUE THREAD

**Issue by saerdnaer** [Podcastindex-org/podcast-namespace#104]
To group chapters, it would be nice if we could also add entries with start and end time to the spec. Reaper named this kind of entries 'regions'. Here is an example project where I used regions to structure markers into groups:

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/40266/98485607-f8481d80-2217-11eb-8f6b-aa70e90ede93.png">

Relates to: #47

**Comment by theDanielJLewis** [comment]
I’ve also expressed interest in supporting an “endTime” option.

Really, I wonder if chapters, sound bites, and excerpts could all be merged i to a single “marks” or similar tag, and then add a tag “type” attribute to differentiate. This would reduce potential redundancy and maybe make implementation easier.

—Daniel

**Comment by daveajones** [comment]
I added “endTime” last week. 

https://github.com/Podcastindex-org/podcast-namespace/blob/main/chapters/jsonChapters.md

**Comment by saerdnaer** [comment]
Oh, I missed that – so we can close this issue. :-)
