### ISSUE TITLE
Should the tag <podcast:locked> have a value?

### ISSUE THREAD

**Issue by dellagustin** [Podcastindex-org/podcast-namespace#11]
Since this tag has a boolean behavior, it could be empty and its meaning could be taken simply by it existing or not in the channel, it would not be necessary to specify a yes or no value.

I can understand though that with the current format it is more human readable.

**Comment by daveajones** [comment]
I see your meaning.  But it feels better to have it be present and with a yes|no to me.  It's such an important declaration of intent that it feels better to have it in there always.
