### ISSUE TITLE
<podcast:image> templated URL?

### ISSUE THREAD

**Issue by saerdnaer** [Podcastindex-org/podcast-namespace#110]
The image servers I typically work with, tend to use templated image URLs where the client can decided which size of the image should be returned, e.g. `https://img.ardmediathek.de/standard/00/57/83/34/30/1016128285/1x1/{w}` or `https://img.br.de/0d532a3a-d9b3-434b-85b0-107700eacdf9.jpeg?width={w}` 

Would it make sense to support such templated URL, to reduce endless prefix repetition?
```
<podcast:images src="https://example.com/images/pci_avatar-{w}.jpg" sizes="1500w, 600w, 300w, 150w" />
```

**Comment by daveajones** [comment]
Interesting idea.  Need more voices on this one.

**Comment by snookfin** [comment]
That is beautiful code but the Buzzsprout images would not be compatible. 

It may be a nice idea for phase 2 to think about short-hand implementations of the phase 1 tags. Just like with CSS you can be verbose or short. Both work in almost every browser and it doesn't break backward compatibility.
