### ISSUE TITLE
xmlns attribute

### ISSUE THREAD

**Issue by dellagustin** [Podcastindex-org/podcast-namespace#113]
I don't know if this would be a breaking change for consumers, but I think we should change the xmlns (a.k.a THE namespace) attribute.

It currently points to a GitHub domain (https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md), I have the feeling it would be better to use a URI that uses the podcastindex.org domain.

I suggest something like https://podcastindex.org/namespace/1.0, and setup a redirect of this url to the documentation in GitHub.

This way you have more flexibility of what you want to use the URL for (like if you move the documentation elsewhere).

### Refs

https://www.w3schools.com/XML/xml_namespaces.asp

> When using prefixes in XML, a namespace for the prefix must be defined.
> 
> The namespace can be defined by an xmlns attribute in the start tag of an element.
> 
> The namespace declaration has the following syntax. xmlns:prefix="URI".

> Note: The namespace URI is not used by the parser to look up information.
> 
> The purpose of using an URI is to give the namespace a unique name.
> 
> However, **companies often use the namespace as a pointer to a web page containing namespace information.**

> A Uniform Resource Identifier (URI) is a string of characters which identifies an Internet Resource.
> 
> The most common URI is the Uniform Resource Locator (URL) which identifies an Internet domain address. Another, not so common type of URI is the Uniform Resource Name (URN).

**Comment by jamescridland** [comment]
I would support this.

**Comment by daveajones** [comment]
This shouldn't break anything that I know of.  Anyone know different?

**Comment by dellagustin** [comment]
@daveajones depends how you parse it, in theory the namespace is defined by the URI in the xmlns attribute, which means

```xml
<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:podcast="https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md" version="2.0">
    <channel>
        <podcast:funding></podcast:funding>
    </channel>
</rss>
```

is equivalent to
```xml
<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:p="https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md" version="2.0">
    <channel>
        <p:funding></podcast:funding>
    </channel>
</rss>
```

but in practice I never saw anyone changing the namespace prefix in rss (in SOAP for instance it is quite common).

What this means is that if someone is parsing the xml based on the namespace, not the prefix (which by the way is the correct way - not that I do it in my app :p), changing the namespace could break the parser.

What I suggest is to announce the change to the community, but recommend to support both namespaces (https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md and the new one) for a grace period and then deprecate the old one.

**Comment by daveajones** [comment]
Yes, I always parse based on prefix instead of xmlns also.  I bet most do.  A change like this has "mixed priority".  It's not super important.  But, it would need to happen sooner, rather than later to keep chaos to a minimum.

**Comment by coldacid** [comment]
I've experienced problems in the past from both prefix changes and namespace URI changes. That said, I think that the namespace URI should change, and sooner rather than later. I would suggest that clients understanding the 1.0 spec should recognize both URIs and treat them as identical.

Also, any XML parser that treats the prefix as the namespace is doing it wrong.

**Comment by coldacid** [comment]
@daveajones any follow-up on this? As mentioned before, the sooner #143 is merged in the better.

**Comment by daveajones** [comment]
Done!
