### ISSUE TITLE
<podcast:value> Per-item override for value tag

### ISSUE THREAD

**Issue by AbelLykens** [Podcastindex-org/podcast-namespace#116]
Thoughts:

 - Allow for overwriting the "main" (root) value tag per episode
 - If I get a guest in my podcast I might want to share revenue for that episode with the guest
 - If there is no value tag in the item, use the mail value tag

**Comment by daveajones** [comment]
Excellent idea. I saw an example of how this would be useful over the weekend.

**Comment by johnchidgey** [comment]
I'd like to add a vote for this too please. On Pragmatic I can foresee wishing to value-split each episode to guests that come on the show. Since there's different guests each episode then this would be different for each episode. Hence I would suggest that the primary Value tag split that would ordinarily go to the host, would then be split between the host and the nominated guest(s) on an episode by episode basis where nominated. Need to ensure the top-level splits are honoured first (podcast app, hosting services etc) before sub-splitting at the Item (episode) level. Just my 2c.

**Comment by satoshisstream** [comment]
#126 partly helps. We could do an overall value tag as we have now. 

Then if there is a value block in an episode, use that to override general tag.

If there is a value block in a CHAPTER, use that to override all.

Most specific use is leading...?

**Comment by daveajones** [comment]
Let’s work this into phase 3. It should be fairly straightforward and we’re already making a change of chapter format to add location data. Seems like a good time to do it.

**Comment by vv01f** [comment]
this maybe just prose what how I understand this, trying to grasp how this will take effect …

1. value data in the channel (maybe that you mean with root value tag) should be taken over defaults in the app (e.g. `suggested` attribute)
2. customized value data by the user in the app should override app defaults as well as any data on the feed
3. per item value data should override the channel (could be mistanken for solving this issue already)
4. per chapter valueOverride #216 should dominate even the item value data
  + this feels like a workaround for my use case: send custom metadata for this time
  + this is also enabling to have a short part (snippets for a mix) being recognized

what I miss:
* a) which data is to be overridden and how should it look like?
* b) I guess it might not be sufficient to manipulate the data given by the value block itself yet.
* c) this might be not just a single attribute but a few instead.
* d) the attributes `customKey` and `customValue` could already solve for a single keyvalue of metadata if that was recognized, just I lack to find an example or statement on the spec for this
* e) what keyvalue pairs need to be addressed with this or which definitely should not?

my usecase in mind was:
(as the time of writing) using satoshistream every podcaster can have the same node publickey in the `address` attribute, so to differentiate a value block with several valueRecipient entries, the metadata used by satoshistream (e.g. feedID or something else sent by the player) needs to be overridden when a guest podcaster has the same node-service as the host.

I imagine the `valueOverride` being e.g. a json (as such part of a chapter datafile?) to enable manipulating more than a single keyvalue besides the costom keyvalue for a single entry would help.

**Comment by AbelLykens** [comment]
Think we have this now @daveajones ? Close?

**Comment by daveajones** [comment]
Yep!
