### ISSUE TITLE
Do we need <podcast:newFeedUrl>?

### ISSUE THREAD

**Issue by dellagustin** [Podcastindex-org/podcast-namespace#13]
There is already the commonly used `<atom:link href="[Feed url]" rel="self" type="application/rss+xml" />`

<podcast:previousUrl> is very good to have, my only concern is that it may not be verifiable and people could use it in an unreliable and/or harmful way - i.e. I list in my feed as a previous url the current or previous url of another show (ok, if that show is verified, this would be easy to detect and resolve, but still worth mentioning for unverified shows).

**Comment by daveajones** [comment]
That's a valid concern.  Needs discussion, or at least guidelines on how to use it properly.

**Comment by jamescridland** [comment]
I use `<link rel="self" href="https://podnews.net/rss"  xmlns="http://www.w3.org/2005/Atom" />` - (is this wrong?)

At first glance, this *does* look as if it's a duplication of a `NewFeedUrl` - I wonder whether Apple only put it there because they didn't want to put Atom tags in?

**Comment by daveajones** [comment]
I must admit to a personal hatred of the `<atom:link rel=“foo”>` syntax. It just makes my skin crawl for some reason.  But we all have to implement that anyway for websub support so I guess I’m jus complaining. :-)

I’m going to think on this a bit.

**Comment by theDanielJLewis** [comment]
Yes, I think it's a necessary tag. [See my thoughts here](https://github.com/Podcastindex-org/podcast-namespace/issues/3).

**Comment by daveajones** [comment]
Let's close this one out.  I think it's fine to stay in there.  It's semantically clear, and creates middle ground between competing silo namespaces.  And, there will always be atom:link around like @jamescridland mentioned.  Redundant? Yes.  But, sometimes that's ok if it serves a broader goal.
