### ISSUE TITLE
<podcast:location> tag spec contains an outdated element

### ISSUE THREAD

**Issue by jamescridland** [Podcastindex-org/podcast-namespace#133]
> locality: (recommended) With a pipe separator from the country code, this is a humanly-readable place name as preferred by the podcast publisher.

This should read:

> locality: (recommended) This is a humanly-readable place name as preferred by the podcast publisher.

...or, even better:

> locality: (recommended) This is a humanly-readable place name as preferred by the podcast publisher for display in an app. Valid values are "Houses of Parliament", or "North Michigan", or "27 Acacia Avenue, Hammersmith". For programmatic use, developers should use latlon or (better) geo-IDs.

**Comment by daveajones** [comment]
Thanks. Will fix.
