### ISSUE TITLE
tag for social media 

### ISSUE THREAD

**Issue by dellagustin** [Podcastindex-org/podcast-namespace#14]
I would like to suggest adding a tag for social media links for the podcast.
I should be allow many times and be located at the channel tag.

It could have this format:
```
<podcast:social platform="[platform slug]" url="[link to social media account]" name="[name of the social media platform]">[social media handle]</podcast:social>
```

example:
```
<podcast:social platform="twitter" url="https://twitter.com/mypodcast" name="Twitter">mypodcast</podcast:social>
```

Reference: tag handle at https://github.com/socialrss/socialrss/blob/master/DOCUMENTATION.md

**Comment by daveajones** [comment]
I like it.  But why the need for the name="Twitter" attribute when the slug gives it already?  What's your thinking there?

**Comment by dellagustin** [comment]
Hi Dave, the slug is not necessarily something you, as a podcast client, would like to show to the user. It is more like a technical identifier. The name is intended as a display name, so that clients have something more human readable and brand friendly to show for slugs that they do not recognize.

It is not a big difference from slug though, the way I see most of the difference would be on the case of the characters (Twitter vs twitter) as slugs are usually all lowercase.

Anyway, I think we can live without the name if you would like to remove it.

**Comment by daveajones** [comment]
I’m just thinking that when I implement this on the index I’m going to build a mapping table of slugs to friendly names by grabbing the slugs file. I would think that would be the best approach on the code side. 

Why don’t we say that it’s an optional attribute. That way it’s there for services that may not appear in the recognized slugs file yet, but it can be safely ignore by aggregators for those where a slug hit happens. 

Does that work?

**Comment by dellagustin** [comment]
Hi Dave, sure, it could be optional.
I thought of the name property mainly aiming client side aggregators that parse the feeds directly, so that it has something user friendly to show on the UI, only for unknown slugs, for server side aggregators that is not so relevant.

**Comment by theDanielJLewis** [comment]
Ah, the complexity of RSS.

I suggest this format:

`<podcast:social platform="twitter" label="[name]">https://twitter.com/…</podcast:social>`

With the optional `label` attribute that could be used to differentiate accounts. For example, each cohost's or guest's account.

This might need to accept either a full URL or the `@username` convention (even accepting it without `@`).

**Comment by dellagustin** [comment]
> Ah, the complexity of RSS.
> 
> I suggest this format:
> 
> `<podcast:social platform="twitter" label="[name]">https://twitter.com/…</podcast:social>`
> 
> With the optional `label` attribute that could be used to differentiate accounts. For example, each cohost's or guest's account.
> 
> This might need to accept either a full URL or the `@username` convention (even accepting it without `@`).

To be honest, I prefer to have the url as a parameter and use the tag's value as the user handle at the social media platform, as I think the user handle is a stronger identifier of the user or account than the url.

Anyway, what is important for me is that the handle and url are provided clearly in separate way to make it easier to parse (i.e. I don't want to have to detect if the tag's value is a url or user handle, nor have to parse different types of urls to retrieve the user handle.

Regarding the usage of `<podcast:social>` for participants (host, cohost, guest), I think we should consider making the tags `<podcast:host>` and `<podcast:guest>` complex tags, like:

```xml
<podcast:host>
  <podcast:name>J. J. Podcaster</podcast:name>
  <podcast:social ...>...</podcast:social>
</podcast:host>
```

**Comment by tomrossi7** [comment]
`I think the user handle is a stronger identifier of the user or account than the url.`

Wouldn't requiring a handle possibly limit other social media platforms? URLs will always exist, I just don't know about handles? I'm hoping this spec lasts for a long time!

**Comment by dellagustin** [comment]
@tomrossi7 I see your point, but still as far as I remember every social media will have some way to uniquely identify a user or account, so it is hard for me to imagine one that will not have an equivalent to the a handle.

**Comment by jamescridland** [comment]
> To be honest, I prefer to have the url as a parameter and use the tag's value as the user handle at the social media platform, as I think the user handle is a stronger identifier of the user or account than the url.

Twitter's URLs have changed at least twice, but their handles have never changed. They also started without being secure.

* http://www.twitter.com/podnews
* https://twitter.com/#!/podnews
* https://twitter.com/podnews

LinkedIn URLs appear to have bits of country domains in them.

* https://au.linkedin.com/in/jamescridland
* https://www.linkedin.com/in/jamescridland/?originalSubdomain=au

URLs ought to be immutable, but they're not in both these cases.

A user handle makes a bunch of sense to use if it's possible to do so. That *might* be parsed when a user enters a URL, but I'd be cautious about using URLs as anything other than "a link that might work".

**Comment by daveajones** [comment]
Social a phase 2 tag.  Let's put this one on the back-burner until phase 1 is finished.
