### ISSUE TITLE
Proposal: <podcast:contactform>

### ISSUE THREAD

**Issue by johnchidgey** [Podcastindex-org/podcast-namespace#159]
Standard RSS XML already includes an owner Email for contacting the podcaster, however many sites also have a contact form as an alternative option. It might be useful to have a standard reference tag for this at the Feed level.

Wrote about it on my blog for further thoughts: [Podcasting 2.0 Addendum](https://techdistortion.com/articles/podcasting-2-0-addendum/)

**Comment by johnchidgey** [comment]
Apologies: I just re-read Phase 3 and found <podcast:contact type="[feedback or advertising or abuse]">[email address or url]</podcast:contact> which could contain the above.

**Comment by daveajones** [comment]
No worries John. Thanks for contributing!
