### ISSUE TITLE
podcast:locked Is owner attribute required or optional?

### ISSUE THREAD

**Issue by cio-blubrry** [Podcastindex-org/podcast-namespace#169]
Is owner attribute required or optional?

**If it is required**
This is problematic for situations where the user is on their own platform. See other namespace issue: https://github.com/Podcastindex-org/podcast-namespace/issues/168 #168 

If the attribute is required, the wording should be changed to indicate as such. There should also be an explanation how this tag works on self-hosted platforms where the podcaster is the judge, jury, and executioner.

**If it is optional**
If it is optional, the language should be changed to indicate as such. The current language implies that it is "critical", which if it is optional (can be used), it shouldn't be critical.

Optional usage implies that "yes" means it is locked (cannot be imported) and "no" means it is unlocked (can be imported),  The verification of the ownership is optional. This leads to another question, will post as a separate issue.

**Comment by tomrossi7** [comment]
> In other words: <podcast:locked>yes</podcast:locked> PowerPress will not allow the podcaster to import the feed. If <podcast:locked>no</podcast:locked> or not set, PowerPress will allow the podcaster to import the feed.

That seems like a fine approach! @daveajones do you see any issues with it?

**Comment by cio-blubrry** [comment]
@tomrossi7 I think you meant to reply to #168
