### ISSUE TITLE
<podcast:valueRecipient> New attribute - CHANGE OF NAME “valueRole”

### ISSUE THREAD

**Issue by brianoflondon** [Podcastindex-org/podcast-namespace#187]
I'm actively writing my Hive version of the Value for Value code and an API for handling on chain pledges.

While writing my code for routing payments and handling splits, which I will put in the network, not in the podcast apps, I real feel the need for a ```role```. I'm looking at the No Agenda value block from the index, @daveajones is putting the Role in as ```(Podcaster)``` after the name. I'm leaving ```name``` empty for some of these splits.

I want ```role``` so that the name can be left blank and I can run time insert an app, and index, a hosting company, or payment gateway (which is the role I'm assigning my code) at run time. I'll know which App is sending the payment and I'll route 1% (at least, can be more if the podcaster decides) to that app.

```
        <podcast:value type="HBD" method="transfer" suggested="0.05">
            <podcast:valueRecipient role="host" name="Brian of London" type="account" address="brianoflondon" split="95" />
	    <podcast:valueRecipient role="gateway" type="account" address="" split="3" />
            <podcast:valueRecipient role="index" name="PodcastIndex.org" type="account" address="podcastindex" split="2" />
            <podcast:valueRecipient role="app" type="account" address="" split="2" />
        </podcast:value>
```

And yes, I know, 95+3+2+2 isn't 100%, I'm testing my re-calc code :-)

**Comment by brianoflondon** [comment]
In the spirit of sharing, here's what my code does after processing that value block. If any of ```gateway```, ```index``` or ```app``` are not defined my service will add those in taking 1%. If a podcaster wants to specifically set a part of the eco system to 0%, right now that will carry through.

My plan is to have a pretty UI, at the point where someone actually makes a transfer and settles up, that is super clear who gets what and how much.

```
Modified Splits: 
{
  "recipients": [
    {
      "role": "host",
      "name": "Brian of London",
      "address": "brianoflondon",
      "split": 93.1372549019608
    },
    {
      "role": "gateway",
      "name": "pod2hive",
      "address": "pod2hive",
      "split": 2.9411764705882355
    },
    {
      "role": "index",
      "name": "PodcastIndex.org",
      "address": "podcastindex",
      "split": 1.9607843137254906
    },
    {
      "role": "app",
      "name": "Learn to Code App",
      "address": "learn-to-code",
      "split": 1.9607843137254906
    }
  ],
  "roles": [
    "host",
    "gateway",
    "index",
    "app"
  ],
  "names": [
    "Brian of London",
    "pod2hive",
    "PodcastIndex.org",
    "Learn to Code App"
  ],
  "addresses": [
    "brianoflondon",
    "pod2hive",
    "podcastindex",
    "learn-to-code"
  ],
  "splits": [
    93.1372549019608,
    2.9411764705882355,
    1.9607843137254906,
    1.9607843137254906
  ]
}
```

**Comment by daveajones** [comment]
Interesting approach. Thanks for sharing this Brian. I like the role. If it’s optional then it could allow better coexistence with different crypto.

**Comment by brianoflondon** [comment]
Having now realised that my "role" is different from the "role" in the Person tag, I'm going to recode my work work to use "valueRole" as the Attribute name instead of role.

I've got a much more limited list of roles right now.

**Comment by brianoflondon** [comment]
I'm also wondering what the ```type``` attribute does in Lightning seeing as it seems to be set to ```account``` in all the examples. I'm considering changing it to be either ```person``` or ```business```. Neither make much difference in Hive terms but it might be useful info down the line.

```
        <podcast:value type="HBD" method="transfer" suggested="0.05">
            <podcast:valueRecipient valueRole="host" name="Brian of London" type="person" address="brianoflondon" split="85" />
	    <podcast:valueRecipient valueRole="gateway" type="business" address="" split="15" />
            <podcast:valueRecipient valueRole="app" type="business" address="" split="2" />
        </podcast:value>

**Comment by vv01f** [comment]
I do not see how o add more than a single means of payment per recipient. is that planned?

**Comment by brianoflondon** [comment]
> I do not see how to add more than a single means of payment per recipient. is that planned?

As the system was first proposed by Dave and Adam, each value block will be for a specific technology rather than specifying multiple payment methods for each recipient.
