### ISSUE TITLE
xmlns namespace validation

### ISSUE THREAD

**Issue by tomrossi7** [Podcastindex-org/podcast-namespace#188]
Has anyone else run into issues with RSS validation after switching the `xmlns:podcast` tag?

`<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:podcast="https://podcastindex.org/namespace/1.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom">`

The [w3.org validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ffeeds.buzzsprout.com%2F1.rss) throws a wonky error `Use of unknown namespace: https://podcastindex.org/namespace/1.0`. We have some customer support from people that aren't getting accepted by Apple Podcasts. They are notorious for just saying its a problem with the feed, but I was just wondering if anyone else has had issues?

**Comment by PofMagicfingers** [comment]
I'm pretty sure that's not what's causing issues with Apple Podcast. 

If you test a feed with googleplay namespace or any custom xml namespace, w3 validator will freak out, but we never had issues (so far) with Apple Podcast even with our custom namespace at podCloud. 

If you ask your customer to insist to know what is in fact the issue they will eventually tell them, it's a pain to get the real reason, but it is possible. It could be a itunes:image cover not in the "good" colorspace format, that's one of the most obscure reason we got to deal with.

**Comment by tomrossi7** [comment]
Thanks for the confirmation @PofMagicfingers!

**Comment by daveajones** [comment]
I'm not seeing a namespace issue with CastFeedValidator either:  https://castfeedvalidator.com/?url=https://feeds.buzzsprout.com/1.rss

**Comment by tomrossi7** [comment]
Yeah, I'm pretty sure its just Apple being lazy.
