### ISSUE TITLE
Phase 3 - alternateEnclosure + 1 more

### ISSUE THREAD

**Issue by daveajones** [Podcastindex-org/podcast-namespace#189]
I'm going to start doing some work on the main readme to prep for Phase 3.  I think what I'm leaning toward right now is "alternateEnclosure" (or whatever we call it) and 1 other tag that is more simple.  Alternate enclosure is going to take a lot of time and debate because there are so many facets to it (bitrates, delivery, etc.) so this other tag we include needs to be fairly easy in principle.

Given the "proposal" issues we have listed now, are there any suggestions for 1 extra tag to include in this round?

**Comment by daveajones** [comment]
Also, before we get into Phase 3, a reminder that our bible here is "[Rules for Standards Makers](http://scripting.com/2017/05/09/rulesForStandardsmakers.html)".  If you haven't read it, do so now.

The principles for discourse on tags is also fairly simple:

1. You don't know everything and neither do I.  (act accordingly)
2. Encourage others, even if their ideas conflict with yours. (you may change your mind)
3. Be very careful with words like "should".  (there are exceedingly few absolutes here)
4. Speak your firm opinions without fear, but be nice about it.  (it doesn't matter how right you are if you act like a jerk)

I say this because people get very passionate about these things, and it's easy to fly off the handle when someone disagrees with you.  Nobody is here because we're getting paid for it.  We're here because it's fun to build the future.  Nothing will rob your joy faster than someone being a dick.

PSA over.  Onward!

**Comment by Inrumpo** [comment]
Even though it turned out that there might not be a need for a new tag per se, I'm of the opinion that implementing the idea of _paged feeds_, as in standard RFC5005 and discussed in #117, would be a useful addition. Since this one does already exist, it might be a more simple one. @eteubert already layed out a possible implementation that was met with some approval.
