### ISSUE TITLE
Seeking opinion from the Podcast Player APP devs: API calls and JSON.

### ISSUE THREAD

**Issue by brianoflondon** [Podcastindex-org/podcast-namespace#193]
I'm starting to work on the system for Podcast Player apps to stream Hive and Hive Dollars (HBD).

I forsee it working like this but obviously I need App devs on board. I had a chat with Martin a couple of weeks ago but I'd love to talk to all of the Podcasting 2.0 App devs. In advance of that, here's my vision. 

My system for registering a podcast and putting in splits is live but only to be played with, I'm sure I'm going to wipe the database numerous times. There is an email loop for checking ownership of an RSS feed taking either the Locked Email or the iTunes owner email direct from a feed. [https://pod2hiveapi.herokuapp.com/](https://pod2hiveapi.herokuapp.com/).

I strongly encourage App devs to get a Hive account! This will be your payment address and I'm going to be pretty upfront about reserving at least 1% splits for Apps, PodcastIndex and the payment gateway. Podcasters can decide to allocate more!

Whilst I don't think I'll open source my gateway, I absolutely see this is as an open PROTOCOL and anyone can come along and do it better/differently. If this is a roaring success I can also see that these api calls could become part of Hive itself in a future chain upgrade (hard fork).

## App records who the producer/listener is.

To start with I'm going to require producers have a Hive account (which is easy and free to get) and join the system by merely identifying themselves to my gateway site. This requirement may be aliviated in the future with "lite" accounts I know are being developed in the Hive ecosystem. Podcasters/creators are always going to want their own Hive account: this is where their value will accrue.

All the app needs to record is their listener's Hive address (3-16 characters, starting with a lowercase letter) and perhaps a privacy true/false flag.

## Listening/boosting

What I'm currently thinking is that when a listening session starts, your app sends an API call with either the Podcast URL or the Podcast Index ID and the GUID of the episode and the Hive address of the listener and their value rate in HBD or Hive per minute (presently Hive is $0.30. HBD is worth roughly a USD).

**Gateway returns a token** and from then on your app can send an api call every minute, or 5 minutes (or whatever we decide) with the token and the amount of time listened. My code does the splits and writes the pledge to the Hive blockchain, I can return a transaction ID if you want.

There'd be a similar API call for arbitrary boosts and comments flagged with when they were made and how much.

All of this will be on the public Hive blockchain and can be read by any app watching the blockchain stream. In addition I'll provide API calls to retrieve comments by podcast and episode (or I'm thinking of writing these to a "post-comment" thread on Hive which would make them visible through dozens of front ends that already exist).

## Privacy

At this point it might be worth implementing a privacy option where users opt in your app (checkbox true/false) whether to publicly acknowledge a payment. If they opt for privacy their sender address will be obscured in the pledge and my gateway will mediate the payment. This requires them transferring funds via the gateway which I'll avoid in the beta phases. I'm trying to keep this trust-less.

## Token or not?

I had original thought your apps would send something like this:

```
POST http://127.0.0.1:5000/hiveress/v1/v4v/pledge/ HTTP/1.1
content-type: application/json

{
    "app-address": "podfriend",
    "app-name": "PodFriend",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "pod-url": "https://www.brianoflondon.me/podcast2/brians-forest-talks-exp.xml",
    "episode": "https://brianoflondon.me/?p=1889",
    "timecode": "10:33",
    "duration": "60",
    "amount":".05",
    "value_type":"HBD",
    "sender":"blocktvnews",
    "boost":false,
    "anonymous":false,
    "broadcast":false
}
```

But I'm thinking the token system would both confirm that the producer using your app is really a Hive user that I know about, and would dramatically cut the repeat info being sent each time. I'm really new to this world of web services as a developer so I'm really looking for wisdom and guidance.

## This is close to being done

I can get all this working in a matter of a few more weeks I think. I have some other real world distractions (like a court hearing in Australia in the first week of March but as that only means sitting in my home office at 3:30am it's not so bad) so I really think this alternative value for value system could be onboarding some beta users and podcasts within 3 weeks if some of the app devs add 3 or 4 api calls.

**Comment by dellagustin** [comment]
Hello Brian, I would prefer to go without the token, as it is less things to handle on app side, but I can live with it.
A few questions:
* a which moment is the listener "authorizing" the transaction of funds from his/her account to the recients?
* how will your app authenticate that the podcast app is allowed to make/trigger transfers on behalf of the listener?

**Comment by brianoflondon** [comment]
> Hello Brian, I would prefer to go without the token, as it is less things to handle on app side, but I can live with it.

Noted, I'm not wedded to it and can probably do with or without. The only thing we'll need is for Podcast Apps to somehow discover that a given podcast is using Hive value blocks. Right now @daveajones is only listing value blocks for Lightning, I'll have to talk with him about that if I'm to avoid podcast apps asking my server if every podcast they're playing is in my list.

The only bare minimum requirement I see is for an App to know the Hive name of the listener (3-16 chars human readable) and confirm they're registered with my site. That's as simple as sending the name to me and getting back an acknowledgement.

> A few questions:
> 
> * a which moment is the listener "authorizing" the transaction of funds from his/her account to the recients?

I foresee three distinct ways that fund transfers happen and I'm working on the first one of these for the beta phase:

### Stage 1 - 
Producers listening to a show are making a stream of pledges. That's what will be initiated by the regular api pings your app will send. My server will write those pledges onto the Hive blockchain (and record them in a db for ease).

This will include splits to the apps, index and gateway taken at this point and it will be 100% obvious where funds are going. There are no cryptic addresses on Hive, Podcast Index is just "podcastindex" and hopefully all the app devs will register something reasonable for their Hive username.

It will be up to listeners to return to the gateway and view a list of all the pledges they've made (which will also show them splits). There will be a "pay" or "send value" button which fire up their local Keychain Browser plugin which holds the user's Active key. This is the key that lets fund transfer happen. Only then will a transfer of Hive or HBD be made.

> * how will your app authenticate that the podcast app is allowed to make/trigger transfers on behalf of the listener?

### Stages 2 & 3

For a beta with engaged users I prefer to kick off with a model that leaves the producers in complete control of fund transfers.

Beyond that there are two systems which I want to offer.

Hive provides a facility to delegate "Key" authority to another party. In the normal course of using Dapps, "Posting Key" authority is very often given and is similar to authorising another account to use your Twitter log in to post. However a site can ask for "Active Key" authority which gives permission to also move funds on-behalf of a user, beyond posting. This is an option I'm considering but I need to talk with the more experienced cryptos of Hive on the best ways to do this safely. I certainly wouldn't want any user who regularly maintains a large Hive balance to do this though there are considerable protections which I can discuss if people are interested.

Additionally, scheduled to be included in the next Hard Fork in a month or two and I'm watching the devs put in pull requests for right now, is a facility for making regular, Patreon style monthly or other frequency payments. The other option is for Producers to have a rolling balance held by the payment gateway on their behalf from which their pledges are drawn down with notifications if they need to top up.

## My Philosophy: as trustless as possible

In the earliest testing phase when I'm dealing with a small subset of engaged and knowledgeable testers, I'm much happier staying out of the business of either my Gateway or the Podcast Apps becoming financial custodians of funds at any point.
