### ISSUE TITLE
Note on "keep existing conventions"

### ISSUE THREAD

**Issue by theDanielJLewis** [Podcastindex-org/podcast-namespace#2]
>  For example, it would make sense to turn `<podcast:explicit>` into a unary element, where it's existence is taken as a "yes" and it's absence as a "no". But, that has never been the standard.

That's not quite true. For Apple Podcasts (although they've flip-flopped a couple times), a show can me "explicit" (`yes`), "clean" (`no`), or unmarked (no tag). It seemed the way the community used these tags provided some good understanding of the maturity level of the content. For example, "clean" would be appropriate for children, "explicit" would be adults-only stuff (content or language), while unmarked would be PG or PG-13 level.

Along these lines, perhaps a `<podcast:contentRating>` tag would be better and it could follow general G, PG, PG-13, R, and X ratings. Or, you could follow the TV ratings style to specifically indicate _what_ content is in the show/episode, like violence, language, sex, etc.

**Comment by daveajones** [comment]
That’s a good idea. I’ll put the rating tag in there like you describe and then folks can comment further to refine.

**Comment by theDanielJLewis** [comment]
Blubrry has something like this, too.

I much prefer a rating system than simply clean/explicit/unmarked. Think, for example, how podcasts like _Sexy Marriage Radio_ or _One Extraordinary Marriage_ should be rated. Both podcasts are about the sexual relationship within the biblical foundation of marriage. So they might get "explicit" in detail, but not profane. Marking it "explicit" would seem to imply that it's profane, but you also can't mark it "clean" because Apple's guidance is that "clean" means appropriate for children.
