### ISSUE TITLE
Payment Intervals clarification

### ISSUE THREAD

**Issue by stucoates** [Podcastindex-org/podcast-namespace#200]
The [documentation](https://github.com/Podcastindex-org/podcast-namespace/blob/main/value/value.md) currently states: "The "time interval" for calculating payments is always 1 minute."

This should be clarified as to whether it relates to actual elapsed time or the "time" moved through an episode.

These values would be very different if the player is playing at 2x speed, or the user is skipping portions of an episode. What would be the impact of skipping back and re-playing the same section?

**Comment by daveajones** [comment]
10-4.  Thanks for this point.

**Comment by dergigi** [comment]
I assume the payment intervals are linked to runtime, thus playback speed has no effect on payment calculation?
