### ISSUE TITLE
<podcast:person href> clarification: Usage as ID?

### ISSUE THREAD

**Issue by saerdnaer** [Podcastindex-org/podcast-namespace#201]
At podlove we are currently discussing the correct usage of the `href` attribute of `<podcast:person>` – Is it allowed to put an URI there? As far as I interpreted the discussion in #8, we were also thinking about using the value of href as more unique identifier than the name of the person itself – especially in context of a podcast directory. 

https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#attributes-5
> href: (optional) The url to a relevant resource of information about the person, such as a homepage or third-party profile platform. Please see the [example feed](https://github.com/Podcastindex-org/podcast-namespace/blob/main/example.xml) for possible choices of what to use here.

**Comment by daveajones** [comment]
Yes a URI is fine. I should update that wording. I consider it more unique as well. Almost authoritative in the absence of a directory.
