### ISSUE TITLE
Proposal: <podcast:format> tag

### ISSUE THREAD

**Issue by agates** [Podcastindex-org/podcast-namespace#208]
_Note: For the purpose of this discussion, I am using the term "podcast" to refer to an RSS feed that uses "The Podcast Namespace."  This is not limited to typical audio-style podcasts and this distinction is important for the context of this proposal._

`<podcast:format>[format Name]</podcast:format>`
Channel
(optional | single)

I propose a new tag to offer a way for "podcasts" to declare the type of medium they present beyond the type of the file and categories.  This is primarily to assist the application in how to display the "podcast" to the user as part of the user experience.

It is similar to the `<podcast:category>` tag in spirit, but different in that `<podcast:format>` would not necessarily be used as a means of conveying context of what the "podcast" is about to the user.  It is intentionally separate to remove any guesswork from hosts/developers on what to do with the content.

Given the non-exhaustive list below, they may be displayed in different ways to the user.  Some applications may even decide to include only one or two.  These are only examples, not suggestions for final format names.

1. Audio podcasts - As we all know and love today, needs no further explanation
2. Videos - While many applications can display video, it's generally a whole different user experience.
3. Music - Often a user listening to music is focused on it and doesn't care about other content
3. Audio books - Generally much longer than regular audio podcasts, users look for different feature sets
4. Novels - Pretty self-explanatory
5. Scientific papers - Similar to novels, but could include features for feedback/notes etc
6. Web Comics 

Since there is generally very little variation in what one would want to include in `<podcast:format>`, it should be a list curated as a standard for hosts and application developers to target.  There can be only only one format assigned per channel.

For example, "Podcasting 2.0" might declare the following to specify that it is an "audio podcast" about "podcasting":
```
<podcast:format>audio-podcast</podcast:format>
<podcast:category>podcasting</podcast:category>
```

A video channel about monkeys might declare:
```
<podcast:format>video</podcast:format>
<podcast:category>monkeys</podcast:category>
```

A scientific journal about particle physics might declare:
```
<podcast:format>scientific-journal</podcast:format>
<podcast:category>particle physics</podcast:category>
```

*cue debate about tag name*

**Comment by theDanielJLewis** [comment]
I think `<podcast:format>` would be better, as "taxonomy" makes me think more of the tags, keywords, categories, and such. Yes, the format is one such taxonomy, but it isn't _the_ taxonomy.

**Comment by daveajones** [comment]
There should be an "audio" format, but that wouldn't need to be specified.  It basically silently exists for completeness.  If no format tag is present, it defaults to `<podcast:format>audio</podcast:format>`

**Comment by agates** [comment]
> There should be an "audio" format, but that wouldn't need to be specified. It basically silently exists for completeness. If no format tag is present, it defaults to `<podcast:format>audio</podcast:format>`. Agreed?

100% yes, I'm not going to get stuck on naming things as long as we document their intentions properly.  I think the list would be similar to the existing categories list (though I feel the ID is unnecessary, personally).

Does a distinction between "audio", "music", and "audiobook" make sense also?  This would allow an application -- though importantly not expect -- an application to easily differentiate between the 3 with different interface types, instead of throwing it all at the user in one stream.  Or heck there might be an application only focused on one of the 3.

**Comment by PofMagicfingers** [comment]
If we differentiate audio, music, and audio book...why not using shows, fictions, educational, music, audiobook

**Comment by daveajones** [comment]
> If we differentiate audio, music, and audio book...why not using shows, fictions, educational, music, audio book?

That starts to blur the line with categories.  I think this tag (if I understand it's intent) is primarily to give a "hint" to the app of what they are about to consume.

**Comment by PofMagicfingers** [comment]
In that case I'm not sure about differentiating audio from music or audio book : they're all audio after all. 

And an audio book is as different from a weekly web show than a serial fictio or an educational program is. 

Why we would have an audiobook format and not a fiction, or educational. Why audio, and why it designate all audio shows that are not music or audiobook?

I do get the idea of knowing which kind of content it is to show an ad-hoc UI, but it seems weird to have "audio" vs audio book vs music, because they all are audio

**Comment by agates** [comment]
> > If we differentiate audio, music, and audio book...why not using shows, fictions, educational, music, audio book?
> 
> That starts to blur the line with categories. I think this tag (if I understand it's intent) is primarily to give a "hint" to the app of what they are about to consume.

I see "format" as "how" the content is handled vs "what" the content is about in a category.  If one would make an argument for a "movie" to be consumed significantly differently from a regular video, that's what I have in mind for this.

The idea is to work with the free-form category suggestion where categories could be anything under the sun but the "format" would remain strict for simplicity of developers, hosts, and even the index for search.

I'd definitely like to hear what you and Adam have to say about that.

**Comment by agates** [comment]
> In that case I'm not sure about differentiating audio from music or audio book : they're all audio after all.
> 
> And an audio book is as different from a weekly web show than a serial fictio or an educational program is.
> 
> Why we would have an audiobook format and not a fiction, or educational. Why audio, and why it designate all audio shows that are not music or audiobook?
> 
> I do get the idea of knowing which kind of content it is to show an ad-hoc UI, but it seems weird to have "audio" vs audio book vs music, because they all are audio

Well... look at the mess of Spotify podcasts.  They got podcasts into my music and it's a giant confusing mess in one interface.

**Comment by PofMagicfingers** [comment]
> If one would make an argument for a "movie" to be consumed significantly differently from a regular video, that's what I have in mind for this.

Yeah I get what you mean. My input on this was IMHO you don't consume a talk show and a fiction in the same way. But they do fall in the same "audio" format. 
You could use audiobook for the fiction, but that's not technically a book, and most of the time, a fiction work include BGM, SFX etc, whereas audiobook mostly is only a voice reading the book.

**Comment by PofMagicfingers** [comment]
> giant confusing mess

Yeah I feel you, but mixing recorded lectures, pure fiction, and web shows (talk shows, etc) is a bit better but not ideal either IMHO.

At podCloud public catalog we use 6 main categories to sort content : Shows (original web shows), Replays (content from past broadcast from traditional radio or web live content), Fictions, Music, Educational, Audiobooks.

The Shows and Replay are most of the time the same type of content, and it's an editorial choice to separate them. But Fictions, Music, Educational, and Audiobooks are consumed in different ways, have different "categories" (or genre) etc. They are different kind of content

**Comment by agates** [comment]
> > If one would make an argument for a "movie" to be consumed significantly differently from a regular video, that's what I have in mind for this.
> 
> Yeah I get what you mean. My input on this was IMHO you don't consume a talk show and a fiction in the same way. But they do fall in the same "audio" format.
> You could use audiobook for the fiction, but that's not technically a book, and most of the time, a fiction work include BGM, SFX etc, whereas audiobook mostly is only a voice reading the book.

Right I was just editing my reply because I re-read yours and I think we are in agreement.

Ultimately I think the format requests would be user, application, and host-driven.  The current primary driver for me is "video" and I'm definitely biased in that endeavor as a video host pushing the boundaries.

However, I can see a scenario where an application would want a cinematic experience dedicated to movies and only movies.  This clears up that prospect across the board without worrying about spelling mistakes, language differences (as this is not supposed to be displayed to the user), and whatever else comes with free-form categories.

It also solves the problem of the possibility of mixed enclosure types, where a video format might include a separate audio-only file for example.  Or maybe someone would have a "book" as both epub and pdf.

**Comment by agates** [comment]
> > giant confusing mess
> 
> Yeah I feel you, but mixing recorded lectures, pure fiction, and web shows (talk shows, etc) is a bit better but not ideal either IMHO.
> 
> At podCloud public catalog we use 6 main categories to sort content : Shows (original web shows), Replays (content from past broadcast from traditional radio or web live content), Fictions, Music, Educational, Audiobooks.
> 
> The Shows and Replay are most of the time the same type of content, and it's an editorial choice to separate them. But Fictions, Music, Educational, and Audiobooks are consumed in different ways, have different "categories" (or genre) etc. They are different kind of content

I think the genre distinction is a good one and I see that as fitting into the existing ecosystem of categories

**Comment by daveajones** [comment]
This is probably a discussion for the show since I can see a need for other voices too. I see the direction y’all are headed in and it feels write.

@PofMagicfingers thanks for fleshing out how podCloud uses those genres. That helped me understand as well.

**Comment by thebells1111** [comment]
Would something like <podcast:tour> be a good fit for this? I can see developing an app that is specifically for audio tours, and needing a way to filter out all of the podcasts from the Podcast Index that don't have a location in the chapters. Returning only the apps tagged as tour from the index would be super helpful.

**Comment by agates** [comment]
> Would something like podcast:tour be a good fit for this? I can see developing an app that is specifically for audio tours, and needing a way to filter out all of the podcasts from the Podcast Index that don't have a location in the chapters. Returning only the apps tagged as tour from the index would be super helpful.

I think it would be ideal for this, actually -- that's the kind of new idea and application I've been imagining we'd see pop up.  It's exactly the sort of thing that's difficult to represent with other search parameters but also changes very little.

**Comment by agates** [comment]
@daveajones, does @thebells1111's suggestion for using this for audio tours make sense?

**Comment by daveajones** [comment]
I think we need a list of possible formats and then which namespace features must be included within each. So, for “tour” the requirements might me transcripts and chapters. And for “video” the requirements could be transcripts and license maybe. This might fill out the idea that specifying a format tells the app what to expect.

**Comment by agates** [comment]
Closing as I think the linked `medium` tag covers the intention of this.

As far as chapter information as @thebells1111 mentioned, I think it would be best to explicitly list out which features a chapter file has in use.  This would be a change to the chapter tag, perhaps denoting when a chapters file has locations by setting features="locations" or something similar.

Separately, if one can make the argument to have an "audio tour" as a new medium type, that would be great as well and should be discussed there.  It's definitely important to avoid trying to do too many things with any single tag.
