### ISSUE TITLE
xmlns document

### ISSUE THREAD

**Issue by tomrossi7** [Podcastindex-org/podcast-namespace#21]
What do you all think about moving entries into a 1.0 XMLNS document as things are agreed upon? This would allow us to begin rolling out some of these standards and include an authoritative XMLNS header. Buzzsprout will be adopting this standard for transcripts and could link to the document from all of our RSS feeds.

**Comment by dellagustin** [comment]
By XMLNS document, do you mean a form of XML Schema, like an XSD file?

**Comment by tomrossi7** [comment]
I don't think we need an XSD file, but we need an authoritative document that can be linked within the RSS that declares the namespace ([some documentation](https://validator.w3.org/feed/docs/howto/declare_namespaces.html)).

For Buzzsprout, we've already [created one](https://rss-extension.buzzsprout.com/1.0/podcast/) since we've already added `podcast:transcripts`. I would rather point to a document that is an agreed standard rather than one we've pushed through alone.

As this group progresses through the various tags, we can move them into an authoritative XMLNS document. This provides a workflow for us to follow and also an authoritative link that can be included in production RSS feeds.

**Comment by daveajones** [comment]
@tomrossi7 I'm fine with that if you think it's the right way to go.  Are you willing to spend a bit and create it here in the repo?

**Comment by tomrossi7** [comment]
Yeah, absolutely. I'll give it a first-go and start with the tags that I think we already all agree on.

**Comment by daveajones** [comment]
Perfect.

**Comment by daveajones** [comment]
Work started so I’ll close this issue.

**Comment by tomrossi7** [comment]
We may want to have a more formal process for when tags are accepted and added to the XMLNS document. Ideally, we would have at least a podcast platform/host and maybe a player agree to to support the tag?
