### ISSUE TITLE
Chapters media type ambiguity

### ISSUE THREAD

**Issue by mpgirro** [Podcastindex-org/podcast-namespace#211]
Hi there,

The [namespace spec](https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#chapters) defines `application/json+chapters` as the preferred media type. In contrast, the [JSON format spec](https://github.com/Podcastindex-org/podcast-namespace/blob/main/chapters/jsonChapters.md) defines `application/audio-chapters+json` as the content type to be used for the served file.

Please clarify which media type is the correct recommendation.

Thanks!

**Comment by daveajones** [comment]
Thanks for catching this. Pretty sure it’s “application/JSON+chapters” but let me verify that first...

**Comment by daveajones** [comment]
It's "application/json+chapters".  I'll fix the spec document.  Thanks for this.

**Comment by mpgirro** [comment]
Thanks for the quick response.
