### ISSUE TITLE
WebVTT support for podcast:transcript?

### ISSUE THREAD

**Issue by agates** [Podcastindex-org/podcast-namespace#217]
Working with some web technologies, I've come across the WebVTT subtitles/caption format.  It's very similar to SRT and seems to be increasing in use on the web.

https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API

**Comment by daveajones** [comment]
@tomrossi7 @snookfin Do you guys see any problem with adding this to the supported file format list?  Seems fine to me.  Video podcasts are a thing.  Even if there aren't a ton of them.

**Comment by snookfin** [comment]
@daveajones I don't have anything against WebVTT, but I would prefer to have a player app commit to supporting it first. I'm not a fan of adding things that devs aren't asking for.

**Comment by agates** [comment]
This is already in use by peertube.  I wouldn't ask for it if it wasn't using it.

Just because you don't consider it a relevant podcast app doesn't mean it's not in use.

**Comment by snookfin** [comment]
I wasn’t aware peertube was on it. I certainly didn’t intend to insinuate anything about relevancy. I apologize for the misunderstanding. ✌️

**Comment by tomrossi7** [comment]
I believe the spec as it is written already supports WebVTT. You could add an example to the docs, but you could do it like this:

`<podcast:transcript url="https://example.com/episode1/transcript.vtt" type="text/vtt" />`

**Comment by daveajones** [comment]
Added example.  @agates do you want to add a WebVTT snippet to the `https://github.com/Podcastindex-org/podcast-namespace/blob/main/transcripts/transcripts.md` file so it's complete?
