### ISSUE TITLE
"Episode" namespace?

### ISSUE THREAD

**Issue by stpp2** [Podcastindex-org/podcast-namespace#224]
(Not sure if this fits the 'proposal' title or not.)

Wouldn't it be a good idea to use separate namespaces for the podcast itself ("show" or `<channel>`) and the episodes (`<item>...</item>`)?

Each can contain similar tags at times, and separating the two might allow more flexibility in the future.

**Comment by daveajones** [comment]
I don't see a need for that personally.  In those scenarios we can just adjust the tag structure to take the needs of each into account.
