### ISSUE TITLE
Chapter location data

### ISSUE THREAD

**Issue by daveajones** [Podcastindex-org/podcast-namespace#232]
I’ve added a location object to the chapters spec if I can get some eyeballs on it. Let me know if anyone sees a problem with the structure. It’s basically just the location xml tag as a JSON object. 

- [Spec](https://github.com/Podcastindex-org/podcast-namespace/blob/main/chapters/jsonChapters.md#the-location-object)

**Comment by douglaskastle** [comment]
What is a chapter here? I think it is confusing, maybe I missed the point.  A chapter is a time index denoting a start or a change in content(is what I think one would define a chapter). Maybe that is what it is with a title? What is it without a title?

Am I right in saying that you are saying that the location is only settable at the chapter level? That does increase the precision, however there might be cases where the location and the chapters don't align.  Would it not be possible to have a time index and at that index it could have a chapter or a location or both?

**Comment by daveajones** [comment]
That would be a use case for a non-toc (i.e. silent chapter).  If the table of contents on a chapter marker is set to false then it won't show up in the jump list in the app ui, but will still allow for triggering things in when that time code hits.

**Comment by chiragnd** [comment]
Could the ‘silence’ of the chapter just be based on the title, ie if a title is not set it wouldn’t show up in the toc. It would work too if you just want an image to show up but don’t want a toc listing necessarily (of course that’s up to the apps to implement correctly so it might make the case for a separate clear flag but just thinking if it’s clear enough from the title). 

The chapter based location tag looks good. 

PS Might be nothing but I see two types of image in the chapters example, a `hasArtwork` and an `img` tag for the chapter.

**Comment by daveajones** [comment]
> Could the ‘silence’ of the chapter just be based on the title, ie if a title is not set it wouldn’t show up in the toc. It would work too if you just want an image to show up but don’t want a toc listing necessarily (of course that’s up to the apps to implement correctly so it might make the case for a separate clear flag but just thinking if it’s clear enough from the title).
> 
> The chapter based location tag looks good.
> 
> PS Might be nothing but I see two types of image in the chapters example, a `hasArtwork` and an `img` tag for the chapter.

Some of the things you see in the spec, like "hasArtwork" is because this spec is also used in static site pages with embedded web players.  We merged the spec with Fredrick Bjoreman's [Chapters App](https://chaptersapp.com/) so that it would be also usable more broadly as a cloud audio chapters spec for those use cases without having to have two different files.

**Comment by daveajones** [comment]
cc: @bjoreman - Did you see the location data spec and the JSON version bump listed here?

**Comment by daveajones** [comment]
@chiragnd I just realized `hasArtwork` isn't defined in the spec doc.  Thanks for pointing that out.  I'll adjust it.

**Comment by bjoreman** [comment]
@daveajones Yes, I'm on it :-). Put the basics of support into my app the other day, and it all made sense. What I really need to do in my case is figure out a nice way of picking locations on a map or something :-)
