### ISSUE TITLE
Questions about adoption readiness of phase 1

### ISSUE THREAD

**Issue by rigdern** [Podcastindex-org/podcast-namespace#233]
I have some questions about adoption of the elements from phase 1 (e.g. the transcript & chapters elements):
1. Are these elements sufficiently finalized to be adopted by podcast creators and players? In general, how can one tell whether a phase is finalized and ready for adoption?
1. Is there a strategy in mind for spreading awareness of the `podcast` namespace and getting its elements adopted by podcast creators and players?
1. Regarding the `<podcast:transcript>` element. The spec lists several supported formats (JSON, HTML, SRT, WebVTT). What's the recommendation for podcast creators? Is it sufficient for them to provide their transcript in just 1 format (are some formats preferred over others)? Or do they need to do the work to provide their transcripts in all supported formats?
1. Is this the proper forum for asking these kinds of questions?

## Additional Background

I am particularly interested in adoption of the `<podcast:transcript>` element. Searching around the internet, I see mentions of podcast transcripts and various podcasts that provide them but they involve just publishing the transcripts on podcast websites. I found very few mentions or usages of the `<podcast:transcript>` element.

I put together [a demo](https://rigdern.github.io/podcast-transcript-demo/index.html?collectionId=1446336657&episodeGuid=Buzzsprout-8212589) of the kind of experience I'd like from podcast players that support the `<podcast:transcript>` and `<podcast:chapters>` elements. Namely, you can search through the transcript and chapters and click on anything that interests you to seek the audio to the relevant location.

**Comment by agates** [comment]
I'm not sure I can answer this but if you're not getting any traction feel free to join us on podcastindex.social.

I believe there's also a telegram group somewhere.

Lastly, this might be a perfect question for our weekly casual developer roundtable every Saturday at 18:00 UTC.  The jitsi link is generally posted on podcastindex.social right before we start.

**Comment by saerdnaer** [comment]
@rigdern to 3: WebVTT seams the most common format.

**Comment by daveajones** [comment]
> 1. Are these elements sufficiently finalized to be adopted by podcast creators and players? In general, how can one tell whether a phase is finalized and ready for adoption?

Anything listed in the official [XMLNS document](https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md) is fully adopted as part of the namespace and is safe to implement.


> 2\. Is there a strategy in mind for spreading awareness of the `podcast` namespace and getting its elements adopted by podcast creators and players?

That's an on-going process.  It's widely known about thanks for media coverage from Podnews, PBJ, social media, etc.


> 3\. Or do they need to do the work to provide their transcripts in all supported formats?

Just go for SRT or WebVTT.  You'll get the best coverage that way.  WebVTT is fairly new to the spec, so SRT may have wider support in the podcast apps.

As @agates mentioned, joining the mastodon at podcastindex.social will let you have a little quicker experience with chatting about implementation and development.  Lots of good devs there.

**Comment by rigdern** [comment]
Thanks for the answers. I'll close this issue and continue the discussion in the other forums you recommended.
