### ISSUE TITLE
[Question] Can I use Anchor and have an automated RSS compatible with the new namespace?

### ISSUE THREAD

**Issue by Atreyu-94** [Podcastindex-org/podcast-namespace#236]
I would love to be able to use CastoPod on hosting, but I can't afford it, since I live in a country with financial restrictions.

I've tried searching but only came up with this way. I would love for my future podcast to be compatible with the new namespace but I have the disadvantage that these platforms still do not integrate it. It may take time to do so. I don't know if my question is off-topic but I am very interested in that question. Greetings!

**Comment by daveajones** [comment]
Answering the question on the title, not currently.  Anchor does not support the new namespace at all.

**Comment by saerdnaer** [comment]
You could set up a proxy on a shared hoster or a static site extending the feed with additional tags.

**Comment by Atreyu-94** [comment]
@daveajones @saerdnaer Thank you! Sorry for my delay, won't that which you say duplicate my feed?

**Comment by saerdnaer** [comment]
If you don't publish the URL of the Anchor Feed, this shouldn't be a problem. And you can configure a redirect in their backend, if you decide to switch later…

**Comment by douglaskastle** [comment]
I use wordpress as my RSS feed, you can input the mp3 from anchor in there and use the RSS feed from the wordpress site.  One should always have there RSS feed separate from the hosting provider any way, it opens up your flexibility to move hosting providers down the road without having to resubmit your feed to all the directory providers, here is something I wrote earlier:

https://medium.com/podonaut/what-is-a-podcast-rss-feed-8afef61adedb

Also keep an eye on castopod and if they implement external URL, you'd be able to do similar (which I opened and they haven't commented on one way or another):

https://code.podlibre.org/podlibre/castopod-host/-/issues/98

**Comment by Atreyu-94** [comment]
@douglaskastle  Very good article but in my case I cannot buy a hosting because my country has severe financial restrictions on citizens. 

That was just the intention of my question. On the other hand, I could not use the plugin so I would have to read the documentation and try to make the editing chapter by chapter by hand in the RSS. Which is quite cumbersome.

The other thing that I have left is to try to program a simple graphical interface to be able to pass the RSS arguments without tormenting myself much. But I'm not a developer so it has a pretty high barrier to entry.

Thank you very much to all :)

**Comment by douglaskastle** [comment]
@Atreyu-94 sorry maybe I should have given you more details. For hosting here you can keep anchor as the place that serves your media. 

Then you need to set up a domain and a website to serve the rss. You at least need a domain name, which can be (eventually) gotten from cloud flare for ~$9 a year, that is about the cheapest you can get. As for the website, you can trick out github with github pages to serve a static site there, as long as it doesn't go over 1GB you should be fine (again the media is not hosted there so it wouldn't count) 

https://pages.github.com/
https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

If you are willing to have the github name in your domain name, you could even do it without paying for your own, though I don't recommend that.

**Comment by douglaskastle** [comment]
@Atreyu-94

Oh BTW this isn't a suggestion of what you maybe could do, I actually did it.

http://github.gurucomedy.com/

That is a static file dump of my main podcast rehosted under github. I tried to get them to host the media too, but they will not upload files bigger than 50 MB. Some of my episodes were below and some were above.

**Comment by Atreyu-94** [comment]
Thank you very much man! From what I see you may not have to pay for the domain either. Take a look at this project:

https://runkod.com

They assure you a domain, ssl certificate and any static site you want to upload. 

There is still the question of finding a static website framework that supports RSS plugins. Otherwise I will need to do it by hand within the RSS file. These days I am going to test these variants, I am not a developer, I will delay, I will comment on the results later.

**Comment by douglaskastle** [comment]
@Atreyu-94 Well for a static site you could do 2 things. 

You can actually do a full install of wordpress on a home machine. it is only visible on one machine, but you can interact and view it in a browser.  Using this framework and the correct plugins (I recommend podlove) you can set up a full php/mysql driven site, then when in the correct state, you can do a static website dump of that site, which can adjust the paths accordingly, and that can be the way you can generate a static site.

https://kinsta.com/blog/wordpress-vs-static-html/

Alternatively, you can use a straight static site generator from the outset. Jekyl is used on github a lot, but this is ruby based.  I use python so pelican it my goto here.  Sadly it podcast/feed support is pretty poor and out of date:

https://github.com/magnunleno/pelican-podcast-feed

it is only used to generate a valid feed, and it is only itunes tags.  

However I had a look at it today and I have started adding some PC20 tags. It is fairly easy once you get going, and you have full control over the structure of the tags if you fiddle at that level.

https://github.com/podonaut/pelican-podcast-feed/tree/pc20_update

Any way this conversation has piqued my interest, I am going to see what I can get up and running this way.  A PC20 compliant website running as close to free as possible. (I have some domain names already, so I may get to cheat here as it doesn't cost me any extra)

**Comment by douglaskastle** [comment]
> Take a look at this project:
> 
> https://runkod.com
> 
> They assure you a domain, ssl certificate and any static site you want to upload.

Oh also on this point.  I think you can get a domain name from them, but it will include xxx.runkod.com in it.  This is free, but you are back again tied to them as a service, it is a pain to move off if you ever do.  You can set them up to do a custom domain name, which is more like it, but you have to come to them with the domain name, so you'd have to pay for that.

I have pulled a few free domain names from here, but you can be very limited in what you get, and you do have to keep renewing it.

https://freedns.afraid.org/

For a static site i would stick with github, there caching and multiple deployments world wide is all backed up by microsoft. It is free, until it isn't. But if you had you own domain, you could then just move to runkod, (or vice versa) in the morning and just keep rolling.

While I am here and talking about cheap/free.  Have a look at internet archive for hosting.

**Comment by Atreyu-94** [comment]
@douglaskastle Ey! Welcome to the conversation. Well, I wanted to implement Castopod and I asked them on Twitter: https://twitter.com/castopod/status/1386919985226866689, they evidently confirmed that they do not support static website generators so they recommend the Cecile tool with the dedicated topic for podcasts: https://github.com/Cecilapp/staticast

About free static website generators I have found these alternatives:

- [Github Pages](https://pages.github.com/)
- [GitLab Pages](https://about.gitlab.com/stages-devops-lifecycle/pages/)
- [Netlify](https://www.netlify.com/pricing/)
- [Runkod](https://runkod.com/): This one, as I mentioned, gives you a free custom domain, ssl certificate and a static website.

Sobre dónde alojar los archivos de audio las alternativas más viables que he encontrado son las siguientes:

- [Internet Archive](https://archive.org/): This alternative has a web player that can be embedded in other websites (I think)
- [Figshare](https://figshare.com/): This is proposed to allow you to upload any type of file and it is proposed to preview it on the web. It also gives you a DOI identifier for each file with the license you choose. The latter helps make it citable and licensed.
- [Hummanities Commons](https://hcommons.org/): Another site like Figshares that gives you a DOI and focused on the humanities. Has a category for podcasts
- [Zenodo](https://zenodo.org/): Another site like Figshare and Hummanities Commons that gives you a DOI and lets you upload audio files with some metadata. It is hosted on CERN servers and I have seen a section for audios (podcasts?)

Of these alternatives, which one would be the best for our listeners? I guess the one with the least latency and the one that allows the most concurrency. So downloads are not a problem for users. But that data is very technical for me, if you are interested and have a way to find out, tell me

Thanks to each of you for helping me with my questions!
