### ISSUE TITLE
Pushing alternateEnclosure over the finish line

### ISSUE THREAD

**Issue by daveajones** [Podcastindex-org/podcast-namespace#238]
Now that we have a full, detailed proposal, what is need to get this one done?

Links:

- [Spec doc](https://github.com/Podcastindex-org/podcast-namespace/blob/main/proposal-docs/alternateEnclosure/alternateEnclosure.md)
- [Issue discussion](https://github.com/Podcastindex-org/podcast-namespace/issues/174)
- [Live Example Feed](https://noagendatube.com/feeds/videos.xml?videoChannelId=73&format=podcast)

Feedback here is appreciated.  I don't see this as something hosts would adopt immediately.  I see it as a "need to have" in order to allow platforms like PeerTube and the like to deliver content to RSS podcasting easier.  With that in mind, I think the current spec works well.  I'd just be interested in what could potentially be showstoppers for implementation by other platforms.

**Comment by daveajones** [comment]
@agates Can you help me understand the usage differences between `rel` and `default` attributes? Maybe it's just a wording thing in the spec, but I'm not fully grasping what they mean.

**Comment by agates** [comment]
> @agates Can you help me understand the usage differences between `rel` and `default` attributes? Maybe it's just a wording thing in the spec, but I'm not fully grasping what they mean.

`default` -- defines whether or not the file defined by `alternateEnclosure` is the _same file_ as defined in `enclosure`.  This is primarily to define more than one way of obtaining this file.

So if you have the same audio `.mp3` file defined in the `enclosure` and wish to provide the same and/or alternative source for the given `.mp3` file, you would set `default` to `true`.

If you had the same audio encoded as a different way, say `.aac` or `.opus`, you would set `default` to `false`.

`rel` -- entire different media from the enclosure.  This will *never* be set to default.  I am not hard set on this attribute however some have expressed interest in it.  It's a way to link two types of media without wholly defining a new item, like a commentary track, bloopers, "making of", or something.  If that's too confusing, I have no issue with removing it.

**Comment by daveajones** [comment]
`rel` seems iffy to me too.  It seems like one of those attributes that look good on paper but never get used in practice.

You know I'm not one to get hung up on naming, but `default` may not be the best choice.  I'm not sure it conveys what it does.  But, I can't think of anything better either.

**Comment by agates** [comment]
Maybe `default` could just be `sameAsEnclosure`?

`rel` would be pretty easy to add if someone comes along asking for the feature, it's one of those "podcasting hasn't been used for this yet" kind of things.  If I recall correctly I only kept it because it was in the original proposal.

**Comment by daveajones** [comment]
I'll make those changes for now.

**Comment by eteubert** [comment]
> length (required) Length of the file in bytes.

How about `bytelength` instead, for clarity? Otherwise it might be confused with the enclosure duration.

**Comment by theDanielJLewis** [comment]
What would you think about changing the tag to `<podcast:altEnclosure>`? It's 6 fewer characters and it might also eliminate potential mistakes writing "alternative" instead of "alternate."

Of course, I'd like to have #239 considered for this, too. But that can probably be an added attribute later.

**Comment by eteubert** [comment]
>  It's 6 fewer characters

Readability is more important a few saved bytes. You might argue that there are many enclosures and  it multiplies, however with gzip even that becomes irrelevant.

**Comment by theDanielJLewis** [comment]
Yes, readability is more important, which seems to also support the idea of preventing confusion between "alternate" and "alternative."

**Comment by agates** [comment]
> Yes, readability is more important, which seems to also support the idea of preventing confusion between "alternate" and "alternative."

This is completely subjective, depending on the person, native spoken language, culture, preferences, etc.  `alternate` is specific enough, `alt` could mean many other things.  And then you get to the question about calling the tag altogether something without enclosure in the name, and we've been down that road already.

**Comment by mitchdowney** [comment]
Hey @daveajones, @RyanHirsch is trying to add liveItem + alternateEnclosure support to podcast-partytime, but the spec says "length" is required for alternateEnclosures, but liveItems won't have a length/duration. Should the alternateEnclosure spec be updated?

**Comment by daveajones** [comment]
Ooh. Yeah let me look at that.
