### ISSUE TITLE
Endorse usage of UUIDs for podcast feeds (and episodes?)

### ISSUE THREAD

**Issue by saerdnaer** [Podcastindex-org/podcast-namespace#243]
Coming back to the iTunes ID discussion in this weekends podcasting 2.0 episode:

I think we should endorse a randomly generated ID for a podcast feed which uniquely identifies a feed, even if the URL to that feed changes. This is basically what the iTunes ID is used for in many third party systems today, which the exception of Google Podcasts which uses a hash of the first URL of a feed it discovers.

Should there be add a new element `<podcast:guid>c26c1f8b-eb53-47ad-8248-8ff276a4539e</podcast:guid>` on the feed level? 

Should we add relations between feeds e.g. for spinoffs e.g. https://fyyd.de/podcast/rabbit-hole which is a short one-time series of https://fyyd.de/podcast/the-daily/ ?
```
<podcast:guid parent="53057254-79bc-4363-bfc9-13e97459babb">c26c1f8b-eb53-47ad-8248-8ff276a4539e</podcast:guid>
```

Should alternate versions of a feed (e.g. the OPUS version, instead of MP3) have the same GUID value?

**Comment by daveajones** [comment]
I'm 100% on board with this.  I think it makes more sense to discuss it in the podping repo though.  And, then what we decide there can be pulled into the namespace if it's going to be applicable:

[Universal podcast identifiers](https://github.com/Podcastindex-org/podping.cloud/issues/1)

**Comment by saerdnaer** [comment]
@daveajones Nevertheless I would also add the  "Universal podcast identifier" to the feed, so it says constant even if the feed is requested via an alternate URL or when it get's moved.

**Comment by daveajones** [comment]
Agreed. This is becoming a bigger discussion. Also talking about it in the channel proposal thread.

**Comment by saerdnaer** [comment]
Just for reference: On the feed level we introduced `<podcast:guid>` for episodes there is already a typical mechanism now documented at https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/other-recommendations.md#episode-guid

**Comment by daveajones** [comment]
So Podlove is producing the feed level guid now?  <podcast:guid> has gained traction quicker than I anticipated.  I need to do a write up on it for larger market so people understand what they can do with it.

**Comment by saerdnaer** [comment]
@daveajones Sorry for the confusion bad wording on my site: "We" meant the Podcasting 2.0 developer community here in this org. It looks like nobody in the Podlove project has implemented it yet, but maybe I will create a PR now... :-) 

(I was just cleaning up some thoughts/issues)
