### ISSUE TITLE
multiple funding tags

### ISSUE THREAD

**Issue by vv01f** [Podcastindex-org/podcast-namespace#244]
for now funding is practically limited to 1 entry as the players do not agreen on how to handle multiple tags.
podcastaddict doesnt defautl to first but only supports one. podfriend didnt show an entry when there was more than one, this may have been be a problem inherited by the index and was fixed – it seems podfriend now defaults to 1st entry.

the spec is not respected by the players it seems, is clarification needed on how to handle those cases?

suggestion: take the first if you support one only.

**Comment by keunes** [comment]
For reference: AntennaPod [will display them all.](https://github.com/AntennaPod/AntennaPod/pull/4933)

And if I'm not mistaken, the [specs](https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#funding) are quite clear, with count: multiple. So maybe non-compliance should rather be reported with those apps?

**Comment by daveajones** [comment]
> the spec is not respected by the players it seems

Welcome to the world of writing specs. 😂

I agree with @keunes - I think the wording is clear. I’m sure that the issue here is one of space restrictions in an app UI. It’s a hard problem.  Filing a “bug” with the apps seems the right solution.

**Comment by vv01f** [comment]
ok, that was done on both anyway. I'll close.
