### ISSUE TITLE
Proposal: XML Schema for podcast namespace

### ISSUE THREAD

**Issue by betpagal** [Podcastindex-org/podcast-namespace#252]
I've created a first draft of a formal XML Schema (XSD) specification for the tags in the podcast namespace. This is created according to the W3C XML Schema spec and supported by most any editor. The idea is to make it easier to create feed documents because the schema will guide you through what is legal at every point in the document and help you choose the valid values. Think Intellisense for the podcast namespace.

As a sample, here's what the syntax looks like:

```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified">

	<xs:element name="transcript">
		<xs:annotation>
			<xs:documentation>
				This tag is used to link to a transcript or closed captions file. Multiple tags can be present for 
				multiple transcript formats.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="url" use="required">
				<xs:annotation>
					<xs:documentation>
						URL of the podcast transcript.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="type" use="required">
				<xs:annotation>
					<xs:documentation>
						Mime type of the file such as text/plain, text/html, application/srt, text/vtt, 
						application/json
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="language" use="optional"> 
				<xs:annotation>
					<xs:documentation>
						The language of the linked transcript. If there is no language attribute given, the 
						linked file is assumed to be the same language that is specified by the RSS 
						language element.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="rel" use="optional"> <!-- can this only be "captions"? -->
				<xs:annotation>
					<xs:documentation>
						If the rel="captions" attribute is present, the linked file is considered to be a closed 
						captions file, regardless of what the mime type is. In that scenario, time codes are 
						assumed to be present in the file in some capacity.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
.etc.
```

I'd like to propose this "formal" schema as an addition to the project to supplement the current DTD, which would be considered the "informal" part of the XML schema.

**Comment by betpagal** [comment]
I've got the following tags defined, along with annotations from the DTD:

```
	<xs:element name="transcript">
	<xs:element name="locked">
	<xs:element name="funding">
	<xs:element name="chapters">
	<xs:element name="soundbite">
	<xs:element name="person">
	<xs:element name="location">
	<xs:element name="season">
	<xs:element name="episode">
	<xs:element name="value">
```

**Comment by daveajones** [comment]
Outstanding!!  Do you want to do a pull request or should I just drop it into the docs folder alongside the current informal spec file?

**Comment by betpagal** [comment]
I don't think the schema is quite ready for publishing. I was hoping to get some eyes on it and have people test it out.

I just have the XSD file and a corresponding sample XML file. I still need to do an MD for it, which will show how to use it. Currently, I have tested on Visual Studio Code.

So I was thinking it would be appropriate to create a folder, xml-schema, and put it in the proposal-docs folder. From there, we can get some comments and then, hopefully, move it into the docs folder.

Is that appropriate? Or do you think we should just put it straight into the docs folder?

**Comment by betpagal** [comment]
Schema placed in docs folder.
