### ISSUE TITLE
API hole

### ISSUE THREAD

**Issue by gogman** [Podcastindex-org/podcast-namespace#253]
There needs to be an API call to get the list of categories and a search feature that searches in a category/categories.

Here is my story:

As a Developer, I want to to provide my user with a selectable list of categories to search, so that the user may search for Podcast with the name "Agenda" and/or the person "Adam" or "John" in the "Comedy" and/or "Drama" categories.

**Comment by daveajones** [comment]
Can you repost this over on the API repo?

https://github.com/Podcastindex-org/docs-api

I can handle there.

**Comment by gogman** [comment]
Done.
