### ISSUE TITLE
Missing project LICENSE?

### ISSUE THREAD

**Issue by dergigi** [Podcastindex-org/podcast-namespace#273]
Please correct me if I'm wrong, but I think the `podcast-namespace` project itself, i.e. the schema itself, does not have a license as of now?

If that is the case, we should [pick a license](https://blog.codinghorror.com/pick-a-license-any-license/), and since not all of it is software, it might be best to pick a documentation license as well.

I guess the licensing choice is up to @daveajones and depends largely on philosophy and vision, i.e. what future direction the project should take. We probably all know our software licenses. For the documentation part there are quite a few options as well - [here](https://dreamsongs.com/IHE/IHE-50.html) is a short overview. Public domain would probably be an option too.

**Comment by daveajones** [comment]
Does anyone have recommendations for which license makes the most sense here?  I’m open to any good idea.

**Comment by joksas** [comment]
I'm not sure, but it probably makes sense to look for inspiration in other organizations managing standards. A couple of examples:  
- [IANA uses CC0](https://www.iana.org/help/licensing-terms), which is essentially a public domain license
- [W3C uses a custom license](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document), which maybe looks similar to MIT license?
- [IETF allows copying but not modifying](https://www.rfc-editor.org/faq/#copyright) for all RFCs

**Comment by genebean** [comment]
My two cents: 
- BSD 3 Clause if you’re super open to people doing anything they want with it. I prefer this over MIT, personally. 
- Apache 2 otherwise 

See https://fossa.com/blog/open-source-software-licenses-101-bsd-3-clause-license/ for some good info.
