### ISSUE TITLE
Suggestion: Use domains rather than slugs for the podcast ID proposal

### ISSUE THREAD

**Issue by amarksteadman** [Podcastindex-org/podcast-namespace#282]
In phase 4, there's a statement about identifying podcasts by ID in different services, which I think is a great idea. I've moved a particular feed around so many times (badly) that there are a couple of duplicates hanging around, so it would be great to be definitive.

In the interests of being definitive, I wanted to suggest using domains rather than slugs for the services listed in `serviceslugs.txt`, as it's less ambiguous. Reverse domain notation feeds like it makes sense here so `com.apple`, maybe `com.amazon.music`... if we consider Google formerly had 2 podcast directories, it might make sense to have `com.google.podcasts` and `com.google.play` (I know the latter no longer exists, but hopefully ou take my point there). It feels like for the most part it prevents people from having to think up a slug for a service, as it should become obvious: in most cases, just reverse the domain name of the directory in question.

Anyway, not by any means a priority, but when I saw this I thought it might be worth a look. Happy to provide a full list we can work towards, if helpful.

**Comment by daveajones** [comment]
I think this makes a lot of sense. I’m fine with doing it this way.

**Comment by saerdnaer** [comment]
Does it really have to be the reverse notation? I personally prefer `domain.tld`... but we have also decentralised identifiers like `mastodon` or `bitcoin`... c.f. https://github.com/Podcastindex-org/podcast-namespace/pull/286/files
