### ISSUE TITLE
<podcast:newFeedUrl> tips

### ISSUE THREAD

**Issue by theDanielJLewis** [Podcastindex-org/podcast-namespace#3]
`<itunes:new-feed-url>` and feed-redirecting are commonly misunderstood by many podcasters (who really shouldn't have to worry about the tech). It seems like some of those misconceptions might be present here, so I want to help clarify.

It doesn't matter what you put in an RSS feed when it's being 3xx-redirected. The feed contents won't load because the header redirects.

But not all podcast-publishing tools hosting providers allow redirects. That's where `<itunes:new-feed-url>` can be used as a pseudo-redirect, but it works for only a few podcast apps and is thus not nearly as effective as a 3xx redirect. It also requires that the feed be accessible and that tag be visible, whereas a 3xx redirect can be placed on a URL with absolutely no file present.

The other way Apple Podcasts and iTunes use `<itunes:new-feed-url>` is to _confirm_ a podcast's new feed. Apple even recommends using it this way.

Here's a typical scenario: Redirect `/oldfeed` to `/newfeed`. Then place `<itunes:new-feed-url>` on the new feed pointing at itself. This helps Apple Podcasts (and maybe some other apps) to more quickly confirm the new feed and change their catalog.

**Comment by daveajones** [comment]
Added clarification around this.
