### ISSUE TITLE
Advise on how to include an open-source podcast player with the podcast2.0 effort

### ISSUE THREAD

**Issue by jaap-dekkinga** [Podcastindex-org/podcast-namespace#329]
I have created an open-source podcast player we're building has the option for listeners to share per second if they liked, disliked, or loved the content. This will result in a heatmap of any podcast on how the listeners feel about the content. 
The podcast player allows the listeners to bookmark podcast moments (~10 sec) and share these bookmarks with their friends.

The podcast player also allows podcast creators to use audio hyperlinks in their content. Audio hyperlinks are the same as hyperlinks you use on your website but then in your podcast. You can make any call to action in your podcast, like visit a website or listen to this other podcast, actionable for your listeners with one click. Enable true interactive audio while measuring with laser precision who is consuming your podcast and also who is engaging with your content. This data enhances the value proposition of your podcast, allowing you to deliver a data-driven return on investment for your advertisers/sponsors.

**Comment by theDanielJLewis** [comment]
Can you link to an example of it in action?

**Comment by jaap-dekkinga** [comment]
This video shows an example of TuneURL: The podcast hosts request people to send her a tweet. When users indicate yes, twitter opens with a prefilled screen: https://youtu.be/HvsfxRTWGiY

**Comment by theDanielJLewis** [comment]
I'm confused. Is it an app, an embeddable player, or a code library for use in any of these?

**Comment by jaap-dekkinga** [comment]
I have created an open-source podcast player with a few unique features:
- the option for listeners to share per second if they liked, disliked, or loved the content
- podcast player also allows podcast creators to use audio hyperlinks in their content (our patented technology), as shown on the video. This is an optional feature that podcast creators can use.

**Comment by theDanielJLewis** [comment]
Um … isn't that what you already said?

**Comment by jaap-dekkinga** [comment]
its an app

**Comment by jaap-dekkinga** [comment]
It's okay if there is no interest. Please let me know and I will focus my attention somewhere else.
