### ISSUE TITLE
Live Chat Tag

### ISSUE THREAD

**Issue by thebells1111** [Podcastindex-org/podcast-namespace#333]
I know `<podcast:socialInteract>`  `interactionLink` would cover this, but adding something like `<podcast:liveChat>` to the `<podcast:liveItem>` tag would make it easier to link to the chat room within an app. It would basically contain a link to a chatroom that ideally should be styled to look good on a mobile screen and be able to be opened in an iframe. This solves the problem of allowing live chat within an app, but simplifies figuring out which of the `<podcast:socialInteract>` may be the one pointing to the live chat.

**Comment by PofMagicfingers** [comment]
Why not, just add an attribute to the liveItem? Something like :
chat="link" seems enough if that's limited to a web url.

Le ven. 28 janv. 2022, 14:15, Steven Bell ***@***.***> a
écrit :

**Comment by thebells1111** [comment]
> Why not, just add an attribute to the liveItem? Something like :
chat="link" seems enough if that's limited to a web url.

That's a great idea!

**Comment by theDanielJLewis** [comment]
I think this is a good idea. I just see some potential hurdles.

Most chat rooms require a login of some sort, whether that's platform-specific (like YouTube chat) or OAuth (such as ChatRoll and similar allow). So a podcast app would need to be prepared for that.

And speaking of YouTube chat, I suggest that any publishing tool that adds the Live tag should auto-detect YouTube Live, Facebook Live, and similar events and auto-suggest the appropriate chat room URL / code.

**Comment by daveajones** [comment]
Going to close this and propose a new, more thorough way to do it that mimics the socialInteract tag.
