### ISSUE TITLE
Keysend should be eventually replaced with AMP or BOLT12

### ISSUE THREAD

**Issue by Kixunil** [Podcastindex-org/podcast-namespace#334]
Keysend was meant to be a temporary solution and will one day be deprecated. It'd be great to eventually replace it with something better. Perhaps have a way to use both for a while to ensure smooth transition.

Some other discussion: https://github.com/breez/breezmobile/issues/743

**Comment by daveajones** [comment]
Would be great to add BOLT12 support to the spec. But, we really can’t even think about that until it’s supported by LND. I think the only software supporting it right now is c-Lightning.

**Comment by daveajones** [comment]
Going to close this until the lightning community comes together around broader adoption of bolt 12.
