### ISSUE TITLE
Support `“imageUrl”: “https://example.com/altrss/image.png”`, alongside episode url

### ISSUE THREAD

**Issue by marek-lach** [Podcastindex-org/podcast-namespace#339]
Support an (optional) **imageUrl** tag, for an unified way for podcasts hosts and clients that support this namespace, _to embed the URL for a square image displayed for the referenced podcast_, so that even this episode title image could be federated accross Podcastindex compliant platforms.

This could be a field next among the url, or the episode title fields.

**Comment by jamescridland** [comment]
If this is a suggestion for the Podcast Index API, I love this idea.

(What would be amazing, but fully understand why it might be a bad idea, is for the image to also be pulled out of the MP3/AAC file if it isn’t present in the RSS feed, and populated into the API. That would be intensely bandwidth-heavy, and probably the worst idea in the world, though potentially possible to use podping and a set of volunteer servers running this as a distributed service).

**Comment by daveajones** [comment]
I’m not sure I understand what’s being asked for. Can you try again to explain it a bit differently?  Apologies if I’m being dense.

**Comment by marek-lach** [comment]
I’m not sure I understand what’s being asked for. Can you try again to explain it a bit differently? Apologies if I’m being dense.

In the specification, there should also be a unified way of where to find and to source thumbnail images for episodes from (by podcast clients), such as specyfying a `“imageUrl”` tag, that would recognisably always be followed by a direct link to the thumbnail .png/.jpg image file.

**Comment by jamescridland** [comment]
The API returns an image URL for each episode anyway, as seen here: https://podcastindex-org.github.io/docs-api/#get-/episodes/byitunesid

An image URL is given in standard RSS, for episodes.

So I'm confused as to what is being asked for here too.
