### ISSUE TITLE
Captions and dynamic content

### ISSUE THREAD

**Issue by jamescridland** [Podcastindex-org/podcast-namespace#37]
Just a question (because I've not been following it very closely)...

Captions - a transcript with a timecode... how does that work with dynamic content insertion, like ads or other content?

If a podcast starts with a 30" shouty ad for a VPN that has been dynamically inserted for listeners in the US, what happens when I listen in Australia and don't get that ad? Are all the captions thirty seconds "out"?

(I wonder how we might fix that, if so. Do the captions go through the ad server along with the audio?)

**Comment by daveajones** [comment]
We modeled it off of what Buzzsprout already has in the wild being used. 

@tomrossi7 How has that impacted you guys so far?  Are you seeing that type of thing?

I’m assuming that most dynamic ad insertion are predefined length blocks. So, it could be just labeled as “ad”.

**Comment by tomrossi7** [comment]
This will be a challenge for podcasts hosts with dynamic content, but outside the scope of our specification. What we've done is provide a flexible format for hosts to provide transcripts with various levels of fidelity (e.g. HTML, SRT, JSON). A transcript that is provided strictly over HTML has the worst fidelity and cannot be used by the podcast player for true captioning. The highest fidelity transcript would be provided over JSON could allow the player to actually highlight individual words or phrases as the audio plays. SRT is middle-of-the-road and allows the player to highlight up to 2 sentences (32 characters each) as the audio plays.

So the host now can decide how to best deliver the transcript content based on the fidelity they can support. If they have dynamic content, they will need to dynamically deliver the transcript or avoid higher fidelity transcripts and just deliver HTML.

How does that sound?

**Comment by tomrossi7** [comment]
@daveajones Buzzsprout isn't doing dynamic content, but if we were, we would render the transcripts dynamically so we could shift the timestamps based on the insertions.

**Comment by jamescridland** [comment]
> we would render the transcripts dynamically so we could shift the timestamps based on the insertions

That would be clever. Nice solution.

I should also point out that [some phones now come with live captions anyway](https://www.youtube.com/watch?v=veRTt94YDX8). Not perfect, but they do seem to work well.
