### ISSUE TITLE
Proposal: A tag to list a few introductory or "listen to these first" episodes

### ISSUE THREAD

**Issue by forteller** [Podcastindex-org/podcast-namespace#385]
After going on for a while, a podcast might end up with one or a handful of episodes which the podcast creator feels are the best starting point for a new listener – because they introduce the topic of the podcast in a good way, or the creator just feel that they are the best episodes for any reason. This might be the very first episode, where the podcaster set out to introduce the podcast, or it can be any other episode(s).
 
It would be really great if it would be possible to use a tag to indicate which episode(s) this is, and have a podcatcher show those to (new) subscribers in any way they see fit.

Thanks!

**Comment by theDanielJLewis** [comment]
We've previously discussed this among other ideas under a `<podcast:featured>` kind of tag.

**Comment by forteller** [comment]
Oh, thanks, I see now that this has been discussed in #281. It seems like many people liked the idea, but it's not been touched since last year. I hope this can be seen as a vote in support of the idea :)
