### ISSUE TITLE
podcast:person - channel/item?

### ISSUE THREAD

**Issue by jamescridland** [Podcastindex-org/podcast-namespace#389]
A question about the specification here.

There are two use-cases that I can see for use of the `podcast:person` specification: "Who hosts (or otherwise is in) this episode?" and "Who hosts this podcast series?" - i.e. episode view and podcast view.

For Podnews, the answer is always... me. So, https://podnews.net/ contains my details in the `<channel>` element.

But for the Podcasting 2.0 podcast, https://feeds.podcastindex.org/pc20.xml doesn't contain any `podcast:person` details in the `<channel>` element. The only details are in the individual episodes.

## So, a question on implementation...

To answer "Who hosts this podcast series?", should a directory be iterating through all the `<item>` values as well as using the `<channel>` values and looking for the hosts?

For Podland, if we were to iterate through individual episode data, then Evo Terra would appear as a "host" (he hosted the podcast a few weeks ago when Sam was off). But he isn't a normal host, and I wouldn't want Evo appearing in "Who hosts this podcast series".

Is the right way to answer "Who hosts this podcast series"...

If `podcast:person` appears in the `<channel>` element, use this data
-else-
iterate through the `<item>` elements and use that data

...and the answer of "Who hosts this episode" is...

If `podcast:person` appears in the `<item>` element, use this data
-else-
fall back to the `<channel>` element and use that data

## If so, a question on the specification

Do we specify this:

**Normally, information should go in the `<channel>` section of the RSS feed.**

**If any data appears in the `<item>` section, this data overrides all data from the `<channel>` section of the RSS feed.**

Example 1:

A show that is normally only hosted by Terry and June should have Terry and June's details in the `<channel>` section. There is no need to place Terry and June's details in the `<item>` section as well.

For one holiday episode Terry was away, and Bill co-hosted the show. In this case, Bill and June's details should be in the `<item>` section.

This will ensure that the Terry & June podcast is correctly shown as being hosted by Terry and June; while the specific holiday episode is shown in a player as being hosted by Bill and June.

Example 2:

A show that is normally hosted by Adam and Dave should have Adam and Dave's details in the `<channel>` section.

Adam and Dave have a guest each week. This week, their guest is John.

In the `<item>` section, data for each of Adam, Dave and John should be listed, since if an `<item>` section is used for `podcast:people`, it overrides the information  in the `<channel>` tag.

**Comment by jamescridland** [comment]
For Podcasting 2.0, incidentally, the data looks like this: lots of "hosts", which I think makes this point.

```
{"name":"Adam Curry","role":"host","href":"http:\/\/curry.com"},"1":
{"name":"Dave Jones","role":"host","href":"http:\/\/dave.sobr.org"},"2":
{"name":"John Chidgey","role":"guest","href":"https:\/\/www.linkedin.com\/in\/john-chidgey\/?originalSubdomain=au"},"7":
{"name":"Dame Jennifer of the PIMP Database","role":"guest","href":"https:\/\/jenniferisaacbuchanan.com\/"},"12":
{"name":"Alby","role":"co-host","href":"https:\/\/getalby.com\/"},"17":
{"name":"Chris Fisher","role":"guest","href":"https:\/\/www.jupiterbroadcasting.net\/"},"20":
{"name":"Tom Rossi","role":"guest","href":"https:\/\/buzzsprout.com\/"},"23":
{"name":"Steven B","role":"guest","href":"https:\/\/curiocaster.com\/"},"26":
{"name":"Josh Chen","role":"guest","href":"https:\/\/www.justcast.com\/"},"35":
{"name":"Nic Ivanov","role":"guest","href":"https:\/\/vizzy.fm\/"},"42":
{"name":"Mitch Downey - Podverse","role":"host","href":"https:\/\/podverse.fm\/"},"45":
{"name":"Oscar Merry","role":"guest","href":"https:\/\/fountain.fm\/"},"58":
{"name":"Der Gigi","role":"host","href":"https:\/\/dergigi.com\/"},"61":
{"name":"John Spurlock","role":"host","href":"https:\/\/podcastsocial.org\/"},"64":
{"name":"Dan Benjamin","role":"guest","href":"https:\/\/fireside.fm\/"},"67":
{"name":"Roy Sheinfeld - Breez","role":"guest","href":"https:\/\/breez.technology\/"},"70":
{"name":"Sir Alecks Gates","role":"host","href":"https:\/\/podcastindex.social\/@agates"},"71":
{"name":"Sir Brian of London","role":"host","href":"https:\/\/podcastindex.social\/web\/@brianoflondon"},"75":
{"name":"Kevin Finn","role":"guest","href":"https:\/\/buzzsprout.com\/"},"82":
{"name":"Thomas Barrasso","role":"host","href":"https:\/\/podlp.com\/"},"85":
{"name":"Alberto Betella","role":"guest","href":"https:\/\/rss.com"},"86":
{"name":"Ben Richardson","role":"guest","href":"https:\/\/rss.com"}}
```

**Comment by daveajones** [comment]
This is a good catch, and clarification in the spec is warranted for sure. I’m not opposed to just including your entire section with examples in the doc.  When it comes to documentation, the more examples the better. It’s one thing most docs lack.

**Comment by daveajones** [comment]
Do you want to drop that in there and I can put eyes on the PR?

**Comment by jamescridland** [comment]
Done!

https://github.com/Podcastindex-org/podcast-namespace/pull/390

**Comment by daveajones** [comment]
Looks like this is handled.
