### ISSUE TITLE
Email Address in the Locked Tag

### ISSUE THREAD

**Issue by tomrossi7** [Podcastindex-org/podcast-namespace#394]
I wonder if we should relax the requirements on the `locked` tag to avoid having email addresses:

`<podcast:locked owner="podcastowner@example.com">yes</podcast:locked>`

Maybe just make it optional?

`<podcast:locked>yes</podcast:locked>`

**Comment by theDanielJLewis** [comment]
I agree with that. I'd actually forgotten that the lock tag even had the email address. Why did we put it in there anyway? If the feed is locked, it shouldn't be migrated. The true owner can remove the lock for the migration, so I really don't see the purpose of the email address's being in the lock tag.

**Comment by daveajones** [comment]
I agree.  Just made the change:

[Locked Tag Doc](https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#locked)

How does that look?

**Comment by daveajones** [comment]
This is handled now.
