### ISSUE TITLE
podcast:imageLarge and variants

### ISSUE THREAD

**Issue by jamescridland** [Podcastindex-org/podcast-namespace#4]
These image variants are marked as:

> This is assumed to point to an image that is 300px to 999px in size.

a) As a developer, I'd really like to have standard sizes, not rough hand-waving "somewhere in this range". If this is deemed unacceptable... I know we want to avoid attributes, but it would be wonderful to have `size="666"` in here, so that we know what size the image is before retrieving it.

b) It would be very helpful, please, to stipulate that images MUST be square.

c) I'm assuming that the image does not need to be the same for these sizes. This is a good thing if so - but it should be documented if that's acceptable.

The use-case is that

![32x32 icon](https://user-images.githubusercontent.com/231941/95644849-d0707780-0afc-11eb-8cc0-4c95a69b87b3.png)

...works really well in tiny sizes, while

![podnews_200x200](https://user-images.githubusercontent.com/231941/95644855-de25fd00-0afc-11eb-8273-712aac339fb8.png)

...works better in larger sizes.

**Comment by daveajones** [comment]
Excellent. Will make these changes.
