### ISSUE TITLE
Chapter Markers

### ISSUE THREAD

**Issue by tomrossi7** [Podcastindex-org/podcast-namespace#47]
I'm documenting this here for discussion. The concern about the impact to the size of the RSS feed as well as the ability to extend what is accomplished with chapter markers has led to the proposal of separating the chapter markers into its own spec.

In the RSS Feed under:
`<podcast:chapters url="htttp://podcasthost.com/episode/123/chapters.json" />`

The actual Chapter JSON spec could be debated separately and could provide more room for growth and innovation independent of RSS.

**Comment by daveajones** [comment]
Should the JSON chapter spec be brought into this repo, or kept separate?  As far as I know, no prior art exists, so either way seems ok to me.

**Comment by tomrossi7** [comment]
@daveajones we are in the same boat with the JSON and SRT spec for transcripts. Maybe we create samples in the doc section and then eventually break them out into their own podcastindex repos?

**Comment by daveajones** [comment]
Sounds good.

The chapters seem dead simple to me.  Could be something as simple as:

```
{
  "version": "1.0.0",
  "chapters": [
    {
      "marker": 0,
      "title": "Intro"
    },
    {
      "marker": 94,
      "title": "Donation Segment"
    },
    {
      "marker": 203,
      "title": "News Discussion"
    }
]
}
```

or as rich as:

```
{
  "version": "1.0.0",
  "chapters": [
    {
      "marker": 0,
      "title": "Intro",
      "img": "http://example.com/podcast/episode/chapter_art1.jpg"
    },
    {
      "marker": 94,
      "title": "Donation Segment",
      "img": "http://example.com/podcast/episode/chapter_art2.jpg",
      "url": "http://example.com/link/to/funding_platform"
    },
    {
      "marker": 203,
      "title": "News Discussion",
      "img": "http://example.com/podcast/episode/chapter_art3.jpg",
      "url": "http://example.com/link/to/article_that_was_discussed"
    }
]
}
```

I'll put the example doc in and we can refine that.

**Comment by daveajones** [comment]
Ok, I have it in the repo now.  If we need to boot this to phase 2 we can.  But, I hope not.  This doesn't seem hard, and seems to have lots of win for the web app guys especially.

**Comment by tomrossi7** [comment]
@snookfin I seem to remember running into an issue with our chapter markers being integers (no fractions of a second). Do we know if other chapter specs use integers?

**Comment by tomrossi7** [comment]
Yeah @daveajones we may want to support decimal so we can support milliseconds. Check out this [id3 spec](https://id3.org/id3v2-chapters-1.0)...

**Comment by vandys** [comment]
Yes, time should be a JS float.  Most multimedia formats at least go down to hundredths of a second.

You should definitely make sure this mechanism suffices for music playback--the minimal fields are artist, title, album, isrc, and label.  The fields don't _have_ to be there, but you will want these if you're marking timepoints of music tracks.

Maybe each record should have a mandatory "event" field, and then if its value is "caption" you can have text to display, "music" you have the music metadata, and so forth.  If there's always a "text" field, then a naive player can just throw up that contents even if it doesn't know from caption versus music.  Music industry standard is "artist - title" for generic labeling, which would be fine for UX purposes.  Caption can just use this "text" field (although you will shortly sink into the quagmire of language support).

**Comment by theDanielJLewis** [comment]
Why push this to yet another file? I think that's over-complicating this and will cause app-developers to not want to support it.

Chapter data is very small, so it's not adding much additional size to a feed—if it's even being used.

Plus, moving this to external JSON also means more bandwidth requirements, more files for publishing platforms to manage, and it seems way more complicated than it needs to be.

While I love that this is JSON (as I think a podcasting "2.0" spec should really be embracing JSON), mixing formats like this seems like it will be dead on arrival and would be a bad direction for us to go.

**Comment by normand1** [comment]
```
     {
      "marker": 0,
      "title": "Intro"
    },
```

What does `marker` refer to in this context? Is this defined somewhere I'm not seeing? Is that a pointer to a seperate object or seconds into the podcast?

**Comment by snookfin** [comment]
@theDanielJLewis - I disagree. Mobile app devs will continue to extract chapters from the audio file. This is for people working in browsers...and most web devs **love** JSON.

Also, the concerns about feed size can't be overstated. There is no need to push all of this data to apps that don't need it. For those that do, we'll deliver it in a friendly format. If we're looking for adoption, I can tell you the chances of Buzzsprout supporting chapter content inside the RSS feed is very low. Feeds are pretty big files already and most subscribers check for updates (and download the entire feed) multiple times per day. It is a massive part of our bandwidth expense and server load.

**Comment by vandys** [comment]
> ```
>      {
>       "marker": 0,
>       "title": "Intro"
>     },
> ```
> 
> What does `marker` refer to in this context? Is this defined somewhere I'm not seeing? Is that a pointer to a seperate object or seconds into the podcast?

It's the time; here as an integer second, but hopefully with full float resolution.

**Comment by normand1** [comment]
There are plenty of properties of an RSS feed that can be arbitrarily long. Just checkout out the <description> tags in this podcast: https://playlist.podcastnotes.org/ or even No Agenda Podcasts. I think it's a missed opportunity to kick these out to a separate spec for fear of the RSS file becoming too large. I don't think there is any evidence of that being an issue.

**Comment by normand1** [comment]
> > ```
> >      {
> >       "marker": 0,
> >       "title": "Intro"
> >     },
> > ```
> > 
> > 
> > What does `marker` refer to in this context? Is this defined somewhere I'm not seeing? Is that a pointer to a seperate object or seconds into the podcast?
> 
> It's the time; here as an integer second, but hopefully with full float resolution.

In that case I'd suggest `startTime` as a less ambiguous descriptor.

**Comment by vandys** [comment]
> @theDanielJLewis - I disagree. Mobile app devs will continue to extract chapters from the audio file. This is for people working in browsers...and most web devs **love** JSON.

Designing for metadata within the audio file means we have to climb this mountain again and again--for mp3, ogg, flac, wav, m4a, alac, ....

I've already noted my own concerns with loading it into the RSS feed.

For completeness, the metadata approaches in industry seem to be:

mp3, with mp3 headers intermingled with audio frames (mp3 supports this, it's completely legitimate)
Meta-framing around an audio stream, like Icecast does
External companion file, such as cue files for audio, SRT and such for movie subtitles

**Comment by vandys** [comment]
> > It's the time; here as an integer second, but hopefully with full float resolution.
> In that case I'd suggest `startTime` as a less ambiguous descriptor.

Or timePoint, as it might otherwise be confused with the start time of the media itself.

**Comment by theDanielJLewis** [comment]
> and most web devs **love** JSON.

That's exactly why I'd rather see podcasting "2.0" be all JSON.

Chapters can be pulled from the MP3 files just fine and without downloading the entire MP3 because chapters are stored along with the ID3 tags in the head of the file. IAB-certified hosts are supposed to count a download only after 1 minute _of audio_, and thus they should be excluder MP3 head information.

However, we are talking only about MP3s, not AACs (which spread chapters through the file) or video.

Still, making separate chapter files means that a podcast with 300 episodes might now _also_ have 300 files with only the tiny bit of chapter information.

I support having chapters in the feed, but _in the feed_, not as external files.

**Comment by tomrossi7** [comment]
With every tag we add to the RSS, we are degrading performance while increasing costs. For podcast hosts like us, this could cost us customers as well as real dollars in bandwidth. **This doesn't mean we shouldn't extend RSS, but we should do it judiciously and concisely when the value outweighs the cost.**

As a app developer, I would actually rather make an additional HTTP call and parse the chapters in JSON rather than deal with more XML.  

`That's exactly why I'd rather see podcasting "2.0" be all JSON.`

Totally agree! Once this spec is completed, we should have a sister spec in JSON. Eventually, everyone could move out of XML and into JSON.

**Comment by normand1** [comment]
> Or timePoint, as it might otherwise be confused with the start time of the media itself.

I wouldn't see that being an issue considering `startTime` would always be wrapped in the context of the chapter tag.

**Comment by daveajones** [comment]
I don't see having an external chapter marker file as any more problematic than having external images to load.  This stuff isn't happening in a web browser, but it's still the web.  And loading external resources is normal.  And, we're talking about maybe 1kb in size for a typical, richly loaded chapter file.  That's nothing.  It's smaller than the album art by a large margin.

If it saves the hosters bandwidth, is negligable for the web devs and gives mobile devs an option they don't even have to use then I think it's the right approach.  The alternative harms the host and doesn't change the devs job at all.

The aggregation would be easier too since I wouldn't have to parse the chapters and store in the DB.  I'd just have to store a link to the chapter json file.

**Comment by jamescridland** [comment]
Perhaps this might help...

Do you **need** chapter information when you pull in the RSS feed? Or do you only need it when you start playing or displaying a specific episode?

I think it's the latter - which means, I think, that it could/should be a separate file.

**Comment by normand1** [comment]
@daveajones Cool, I think the I think the worry over host bandwidth is exaggerated, but everything else is good reasons I hadn't heard yet.

**Comment by normand1** [comment]
> Do you need chapter information when you pull in the RSS feed? Or do you only need it when you start playing or displaying a specific episode?

@jamescridland You could make that same argument for everything that's not the podcast item enclosure so I don't see the point.

**Comment by daveajones** [comment]
> @daveajones Cool, I think the I think the worry over host bandwidth is exaggerated, but everything else is good reasons I hadn't heard yet.

Tom and Kevin are running a large podcast hosting company with 300,000 feeds in production.  If a feed has 20 episodes and we figure an extra KB and a half per episode for chapter markers (could be more) this means almost 10 more Gigabytes in bandwidth per feed pull cycle across their catalogue. This could easily be a terabyte per day difference when you think of everyone that’s polling them. It’s a real concern.  We don’t see it from our side.  But they have to pay those bills.

The external file option is a good balance here. It doesn’t hurt the aggregators at all and app devs can go ahead and start playing the episode as they pull the chapter file in the background and then overlay it as an async operation.

This feels like the right approach. 

There’s no such thing as a “perfect” spec. Balance is what we’ll have to shoot for in these issues.

@normand1 Are you parsing the feeds directly in your app? If so are you willing to do some sandboxing on this method with HyperCatcher? If so I’ll put this in the PC20 feed for you to test.

**Comment by vandys** [comment]
> The external file option is a good balance here. It doesn’t hurt the aggregators at all and app devs can go ahead and start playing the episode as they pull the chapter file in the background and then overlay it as an async operation.

For all of my use cases, this exactly pins down the central point.  This external file _only_ needs to be accessed for the tiny fraction of podcasts which are actually played.  I'd guess easily a 20:1 ratio of what's seen in the podcast browser as compared to what they click on to start streaming.

**Comment by daveajones** [comment]
With regards to the name of "startTime", "marker", etc.  Is there prior art here?  What does the a/v editing industry call this type of time point within a media?

**Comment by normand1** [comment]
@daveajones 
> With regards to the name of "startTime", "marker", etc. Is there prior art here? What does the a/v editing industry call this type of time point within a media?

Existing Podcast chapters use ID3v2 Chapter Frames use "start time" as "millisecond offset from start"

**Comment by normand1** [comment]
> @normand1 Are you parsing the feeds directly in your app? If so are you willing to do some sandboxing on this method with HyperCatcher? If so I’ll put this in the PC20 feed for you to test.

Yep absolutely, my whole app revolves around podcast chapters and I'm parsing them a couple different ways now. I will definitely start using whichever method is agreed upon here as soon as there are feeds up that use this tag.

**Comment by vandys** [comment]
CUE files call this field "INDEX"; srt just has them there with no name.  (I'm comfortable with you just picking one, Dave.)

**Comment by daveajones** [comment]
If ID3v2 already uses start time then let's stick with what you suggested: "startTime" and a float for millisecond precision if needed. I'm building a test file right now to insert into the PC20 file and you can test it out @normand1 .  Will aggregate it next so it comes through the index API also so that @MartinMouritzen can test too.

**Comment by daveajones** [comment]
I have a sandbox feed for testing your apps against the new tags here:  https://noagendaassets.com/enc/pc20sandbox.xml .  It's feed id 1318635 in the index if you're using the API.  It has the chapters tag in episode 7.

Note that I changed the chapters tag to <podcast:chapters> in the spec.  It was incorrectly still listed as <podcast:chapter>.

The "marker" property was changed to "startTime" in the JSON format.

**Comment by thejeshgn** [comment]
Prior Art - chapters from Podlove community

https://podlove.org/simple-chapters/

Apps like AntennaPod already support it

**Comment by daveajones** [comment]
> Prior Art - chapters from Podlove community
> 
> https://podlove.org/simple-chapters/
> 
> Apps like AntennaPod already support it

I saw that spec. Are there any hosting platforms producing those in-feed chapters that you know of?  That seems to be the difficult part for hosting companies with in-feed chapter markers. It potentially adds a lot of extra feed size.

**Comment by KieranMcKeefery** [comment]
> > Prior Art - chapters from Podlove community
> > https://podlove.org/simple-chapters/
> > Apps like AntennaPod already support it
> 
> I saw that spec. Are there any hosting platforms producing those in-feed chapters that you know of? That seems to be the difficult part for hosting companies with in-feed chapter markers. It potentially adds a lot of extra feed size.

Yeah I agree with @tomrossi7 bandwidth costs are a big factor for us podcast hosts, we love to adopt new approaches but if we can agree ways to do it better - you will see much more adoption across podcasts hosts.

**Comment by daveajones** [comment]
@KieranMcKeefery I'm pretty excited about this tag referencing an external JSON chapter marker file.  The ability to include rich content into a podcast without it burdening the feed itself seems like a real pipeline for innovation.

**Comment by saerdnaer** [comment]
Related: https://github.com/Podcastindex-org/podcast-namespace/issues/103

**Comment by vandys** [comment]
Podcasters call them chapters.  Timed information on music shows (artist, title, ...)  is kept in a "cue" file; often the data is called "metadata".  The uses supported here go beyond that; it can be part of the content itself (I foresee a time when people complain because the podcast is no longer intelligible without viewing the associated contents--tables, graphics, whatever).  "marks" is nice in that it's pithy and technically accurate--but it is not evocative of the function.  It's really more like a slide show that goes with the speaker?

**Comment by benjaminbellamy** [comment]
I’m just wondering: shouldn’t the mime type for srt be application/x-subrip ?
