### ISSUE TITLE
podcast:funding direct (Bitcoin Lightning) payment requests

### ISSUE THREAD

**Issue by AbelLykens** [Podcastindex-org/podcast-namespace#53]
Hi!

Would `podcast:funding` be able to hold a lnurl [1]? It's an encoded Bitcoin Lightning payment request; so not a a http link per se. 

Would look like:

    lightning:LNURL1DP68GURN8GHJ7UM9[..]CMYXYMNSERXFQ5FNS

and ideally the wallet app of the user would open this url. Possibly a special attribute would be needed to detect "direct payment requests" instead of trusting it's a web link. There will possibly be more platforms so I'm thinking having a bitcoin/lightning-specific tag might not be the best idea.

Wonder what you think. Would be cool to have this implemented in the first new namespace. I think being able to pay a podcaster directly from a bitcoin lightning wallet would be great.

Thanks for considering!

[1] https://github.com/btcontract/lnurl-rfc

**Comment by fiatjaf** [comment]
I believe you can use `bitcoin:anything` or `lightning:anything` already and be able to click it no matter what the rendering engine the app is using, just like `mailto:` and other things, and as long as your browser or other app support that scheme you'll be able to open and handle it.

**Comment by daveajones** [comment]
Yes I think this should fit into the funding tag just fine without any modification. Is there a standardized scheme slug for triggering lightning wallets to open on mobile already?

**Comment by fiatjaf** [comment]
`lightning:` does it I believe.

**Comment by daveajones** [comment]
Sound like all the bits are there. Let’s try it out when the tags are formalized.

**Comment by tomrossi7** [comment]
Can we agree to make the platform slug optional? Buzzsprout has never required this from our users, simply a URL for funding. For example, some podcasters provide links to paypal, while other just link to their own donation page on their website.

**Comment by daveajones** [comment]
Yep.  Optional is almost always the right way to go.

**Comment by fiatjaf** [comment]
I have not much experience with podcast player apps, but the one I'm currently using, "pocket casts", doesn't not make `lightning:...` links underlined or clickable.
