### ISSUE TITLE
Capitalization vs. hyphenation on multiword tags.

### ISSUE THREAD

**Issue by theDanielJLewis** [Podcastindex-org/podcast-namespace#56]
Maybe this has already been decided, but I think we need to have a clear standard on capitalization vs. hyphenation. For example:

`<podcast:newFeedUrl>` vs. `<podcast:newfeedurl>` vs. `<podcast:new-feed-url>`

[The RSS spec](https://cyber.harvard.edu/rss/rss.html) favors lower camel case (`likeThis`), but the "iTunes" spec favors hyphens. The "Google Play" spec doesn't have multiword tags.

I think we should stick with lower camel case.

**Comment by daveajones** [comment]
I agree.  The hyphenation is jarring every time I see it.  I don't know why they did that.

**Comment by tomrossi7** [comment]
It really is just whatever people are used to. We develop in a Ruby world and are used to underscores and hyphens. While I do prefer that, I recognize I'm in the minority! I think the camel case is the best approach.

**Comment by KieranMcKeefery** [comment]
> It really is just whatever people are used to. We develop in a Ruby world and are used to underscores and hyphens. While I do prefer that, I recognize I'm in the minority! I think the camel case is the best approach.

I remember getting some legacy code from a well known insurance company in the UK and it had all 3 with no code comments, could have passed out.

Either way @theDanielJLewis it's camel case for me any day of the week :-)

**Comment by tomrossi7** [comment]
@KieranMcKeefery I was looking at some transcript JSON from AWS with @daveajones and it had both formats in the *same* JSON file!

**Comment by daveajones** [comment]
lol.  I saw that too.

**Comment by daveajones** [comment]
camelCase
