### ISSUE TITLE
podcast:alternateEnclosure

### ISSUE THREAD

**Issue by jamescridland** [Podcastindex-org/podcast-namespace#6]
This is a great idea, and one of the reasons I've wanted to consider a rather more breaking change to RSS.

1 - Questions:
* Can you have more than one alternateEnclosure? A use-case might be a video podcaster with a high and low bitrate video feed and an audio feed. Same feed, same show, different media files.
* What is the default? Is it the standard enclosure? Or...?

2 - Suggestion: Could I please suggest an optional "title" attribute for UI purposes? While it may be programmatically possible to guess on "low quality" and "high quality", or to choose video vs audio, it's harder to offer accessible versions of the same file - a video with captions added, for example, or a video with audio description for people with sight difficulties?

One example:

**<podcast:alternateEnclosure type="audio/x-m4a" length="1540076" bitrate="80" title="Audio - low bitrate">https://chtbl.com/track/podnews.net/audio/podnews201009.m4a</podcast:alternateEnclosure>
<podcast:alternateEnclosure type="audio/mpeg" length="2534548" bitrate="160" title="Audio - high bitrate">https://chtbl.com/track/podnews.net/audio/podnews201009.mp3</podcast:alternateEnclosure>**

An example for video

**<podcast:alternateEnclosure type="video/mp4" length="11540076" bitrate="512" title="Full video version">https://example.com/video.mp4</podcast:alternateEnclosure>
<podcast:alternateEnclosure type="video/mp4"" length="11540076" bitrate="512" title="Video with audio description">https://example.com/video-ad.mp4</podcast:alternateEnclosure>
<podcast:alternateEnclosure type="video/mp4"" length="11540076" bitrate="512" title="Video with captions">https://example.com/video-capt.mp4</podcast:alternateEnclosure>**

**Comment by daveajones** [comment]
Can you have more than one alternateEnclosure?  Absolutely.

What is the default? Is it the standard enclosure?  Yes, the default is the <enclosure>.  The <podcast:alternateEnclosure> are always 'alternative' versions.

Titles:  I think this is a great idea.  Optional is the right way to go.

**Comment by daveajones** [comment]
Done.  And, added a new use case for using this tag in the channel as a trailer or intro media for the podcast.
