### ISSUE TITLE
Feelings on <podcast:alternateEnclosure>?

### ISSUE THREAD

**Issue by daveajones** [Podcastindex-org/podcast-namespace#62]
How are we feeling about this tag?  I've seen very little comment on it, but I know it's something that has been mentioned as needed for alternate bit rates and such.  I see it as being used very infrequently.  But, when needed, could be a great help.  Is there any downside to this, being as how it's optional?

**Comment by tomrossi7** [comment]
What if we push any tags into phase 2 that aren't going to be implemented by at least one hosting company and one player? Or what if we say a tag will not be adopted until at least one hosting and player company agree to implement it?

**Comment by daveajones** [comment]
That sounds reasonable for this stage in the game.
