### ISSUE TITLE
<podcast:funding> does not consider prior art

### ISSUE THREAD

**Issue by mattbasta** [Podcastindex-org/podcast-namespace#65]
There are multiple examples of prior art related to `<podcast:funding>`. The tag in spec very closely aligns with RawVoice's `<rawvoice:donate>` tag. The most notable (and well-supported tag) is RadioPublic's:

https://radiopublic.com/schema/1.0/#action

RadioPublic provides `<rp:cta>` and `<rp:action>`, which allow you to craft a tag like this:

```
<rp:cta headline="Headline" subtitle="Subtitle">
  <rp:action class="financial" disposition="positive" href="...url..." label="Donate" />
</rp:cta>
```

This implementation has the following advantages:
- Custom verb for financial contribution
- Not financial donation-specific (`class` can be extended to other CTA types)
- Context can be added beyond the scope of a single button or link (with `headline` and `subtitle`)

I'd suggest adding additional attributes or tags to allow podcatchers to create UIs that are more expressive than a single button or link.

I'd strongly recommend replacing the wording "string length" with "string character length", and increasing it beyond 128: some languages which make heavy use of diacritics may be artificially limited to short CTAs, which biases the spec towards Latin-derived languages.

**Comment by daveajones** [comment]
We did consider prior art like rel=“payment” and rawvoice. But also are trying to balance having a complete, self contained spec, minimizing complexity and minimizing the tag burden on hosting platforms. Those are all important. This all really lives and dies at the host. 

The rp tag is very rich but also complex.  Tags can always be expanded in later phases. It was important to keep things to only what was needed as to ease the implementation burden. 

The other thing we are guided by in the RFSM is the idea of writing the spec in plain language.

Your idea to expand string length for mb languages is good.
