### ISSUE TITLE
Add Funkwhale

### ISSUE THREAD

**Issue by MichaelHinrichs** [Podcastindex-org/podcast-namespace#657]
https://www.funkwhale.audio/

**Comment by a-kenji** [comment]
Where? To What? And Why? Are you sure this is the right place for this issue and with an appropriate amount of context?

**Comment by MichaelHinrichs** [comment]
To this. https://podcastindex.org/apps

**Comment by saerdnaer** [comment]
Create a PR against https://github.com/Podcastindex-org/web-ui/blob/master/server/data/apps.json

**Comment by MichaelHinrichs** [comment]
I was SURE this was the correct repo that the link on the apps page took me to.
