### ISSUE TITLE
platform attribute on <podcast:funding> should be removed

### ISSUE THREAD

**Issue by mattbasta** [Podcastindex-org/podcast-namespace#66]
The `platform` attribute on `<podcast:funding>` should be removed. Podcatchers can use this attribute to hide links to support podcasts on platforms which the developer does not agree with.

Consider the (hypothetical) case where Spotify were to use this attribute to ignore `<podcast:funding>` tags which set `platform="patreon"` to drive podcasters to use Anchor's donation platform instead.

Service slugs do not meaningfully improve the user experience and expose information which could be abused by developers.

**Comment by tomrossi7** [comment]
> Service slugs do not meaningfully improve the user experience

I agree with this for pretty much all of the service slugs.

**Comment by daveajones** [comment]
The slugs had good intention.  But, have proven to be a burden across the board.  And, at this point, my sense is nobody will adopt it.  Censorship of any of the tags can happen by targeting the domains in the href/url being linked to.  So, I don't think this stops that potential.  But, I agree that the slugs are probably DOA.

**Comment by mattbasta** [comment]
As a note, censorship can be avoided with custom domains here. So all is not lost on that front. It's a easier to write a cheeky `if` statement than it is to cURL a domain to check its owner.
