### ISSUE TITLE
Podcast chapters JSON format should consistently match ID3v2 spec

### ISSUE THREAD

**Issue by mattbasta** [Podcastindex-org/podcast-namespace#69]
The ID3v2 chapters spec defines a number of useful values which should be mirrored in the JSON spec:

https://id3.org/id3v2-chapters-1.0

- `endTime`: Allows chapters to be non-adjacent. E.g., for ad breaks, post-roll, etc.

The chapters header also defines sub-frames which allow additional information. Besides a title, chapters can have other metadata like speakers, a description of the chapter, and more. It may be useful to allow a `metadata` member for chapter objects, which is defined with the following (TypeScript) definition, using [template literal types](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#template-literal-types):

```typescript
type ProprietaryPrefix = string; // e.g., "pinecast"

type Metadata = {
  type: 'description' | `-${ProprietaryPrefix}-${string}`;
};
type Chapter = {
  startTime: number,
  title: string,
  img?: string,
  url?: string,
  metadata?: Array<Metadata>,
};
type ChaptersDocument = Array<Chapter>;
```

**Comment by coldacid** [comment]
If you were to add `endTime` to your TS definition, it'd be optional yes?

**Comment by daveajones** [comment]
I think I made that change in the docs yesterday.  Yes, it's optional.
