### ISSUE TITLE
<podcast:transcript> different formats / support for captions

### ISSUE THREAD

**Issue by jamescridland** [Podcastindex-org/podcast-namespace#7]
A transcript might [be in HTML](https://podnews.net/article/dan-granger-david-field) and have formatting applied to it. That is best handled as a link to an external website.

A transcript might be in raw text, without formatting. That is best handled internally within a podcast app.

A caption is also a transcript - but with additional timing information within it. My suggestion is that this might live in this as well.

As a suggestion therefore (and I don't know how to deal with more than one):

**<podcast:transcript type="text/html">[url to a website]</podcast:transcript>
<podcast:transcript type="text/plain">[url to a text file]</podcast:transcript>
<podcast:transcript type="text/srt">[url to a SRT captions file]</podcast:transcript>**

This would enable this tag to be used for captions as well as transcripts, and would add flexibility. Of course, a text/plain file can be viewed in a web browser as well; though a text/srt file (or the text/ts file) may be a little harder to do so.

As an addition - I wrote an article about the [differences between transcripts and closed captions](https://medium.com/@JamesCridland/kahlimah-jones-vs-gimlet-the-fight-for-podcast-accessibility-dfcb731d9d7f?source=friends_link&sk=f209442fb0107cca0f52c73e78d7b6b4) on Medium (that's a friend link and will go past any paywall). They are different, but I think it can work here to combine them into one tag, given they're different filetypes by necessity.

**Comment by daveajones** [comment]
I'm partial to different element names myself.  I see no issue with having a podcast:transcript and a podcast:captions element.  It makes the aggregator code easier since you know what you're looking for ahead of time.  Otherwise you have to sort of reverse engineer it from the type attribute.

I'll add the type attribute and expected uri content now and leave this open to hash out further.

**Comment by jamescridland** [comment]
I'm cool with that. :)
