### ISSUE TITLE
<podcast:chapters> should have a mandatory media type

### ISSUE THREAD

**Issue by mattbasta** [Podcastindex-org/podcast-namespace#70]
Allowing any chapter format provides no prescriptive guidance to podcast apps for required support. If a podcast hosting service serves chapters with a `text/plain` file, it's not useful to podcast apps (unless they manually implement this support). Strongly defining support guarantees that implementors of the tag (for both hosts and apps) all speak the same language.

I propose defining a [media type](https://en.wikipedia.org/wiki/Media_type):

```
application/audio-chapters+json
```

This media type should represent the chapters format specified in the `jsonChapters.md` file. Unlike `application/json`, which represents any JSON format, this specifically requires support for the format defined in this spec. This is consistent with the media type for RSS, `application/rss+xml`.

I strongly recommend against allowing any media type, or an ambiguous JSON media type.

**Comment by tomrossi7** [comment]
Interesting! This would apply to transcripts as well since we are prescriptive for that json format as well (`application/transcript+json`).

**Comment by daveajones** [comment]
This seems fine to me.  Again, the mandatory language will only exist in the spec itself.  Many will ignore it.  I know we fought that for years with RSS.  Many still serve it as text/plain to this day.  Trying to coerce it seems fine though.
