### ISSUE TITLE
<podcast:location> should encode country and locality information as an attribute

### ISSUE THREAD

**Issue by mattbasta** [Podcastindex-org/podcast-namespace#71]
The node value of `<podcast:location>` does not contain purposefully human-readable text. Country and locality should be specified as attributes and the tag should become self-closing: requiring an extra parsing step for the node value adds unnecessary complexity.

**Comment by daveajones** [comment]
@jamescridland Thoughts?  I'm fine with this.

**Comment by jamescridland** [comment]
Fine by me.
