### ISSUE TITLE
<podcast:location>'s purpose is not well-specified

### ISSUE THREAD

**Issue by mattbasta** [Podcastindex-org/podcast-namespace#73]
`<podcast:location>` does not define when or how it should be used. It does not say, for instance, whether it should be used to describe where a podcast is recorded, the location a podcast talks about, or some other value.

In the case of an item, where the spec allows multiple location tags, it is unclear how a consumer would disambiguate multiple locations.

Additionally, no guidance is provided on the precision of the `latlon` value: `latlon="7.0,-2.0"` is perfectly valid, but represents an area up to over 100x100km large. Guidance about precision should be defined to both specifically describe the intended location, but also to protect privacy by avoiding unnecessarily detailed information about persons.

Since the use of this element is unclear, I'd strongly recommend removing `<podcast:location>` from the spec until a compelling need for it presents itself, whereupon additional metadata attributes can be specified for the tag, or updated to include missing context.

**Comment by jamescridland** [comment]
> It does not say, for instance, whether it should be used to describe where a podcast is recorded, the location a podcast talks about, or some other value.

Good point. [This closed issue](https://github.com/Podcastindex-org/podcast-namespace/issues/5#issuecomment-708836838) gives the suggestion "Its purpose is to help discovery of podcasts containing local content". Would you like to submit a pull request?

> In the case of an item, where the spec allows multiple location tags, it is unclear how a consumer would disambiguate multiple locations.

An episode of a travel show is half from Manhattan, and half from Stockholm. Searching for a "podcast relevant to Manhattan" or a "podcast relevant to Stockholm" should return that podcast. If there's a fancy map in a podcast app, it might display both of these points.

> no guidance is provided on the precision of the latlon value

Indeed. An area 100km by 100km large is absolutely fine if you want to describe a state or a small country, which the spec allows. Similarly, the spec allows a place ("The Houses of Parliament") for which five decimal places is adequate. Are we right saying...

**Lat/lon precision:** we recommend one decimal place for a country or state, four decimal places for a city; five decimal places for a place. More precision may result in better discovery, but could have privacy tradeoffs.

> I'd strongly recommend removing <podcast:location> from the spec until a compelling need for it presents itself

I don't like custard, but I don't generally recommend removing it from all restaurants until a compelling need for it presents itself. Normally I try to understand what the hell people see in custard. I'm told some people quite like it.

**Comment by daveajones** [comment]
The `latlon` description says:  "A latitude/longitude point reflecting the location associated with this show or episode. This could be where it is made, or alternatively a location which features in the podcast."

More wording to this effect can be put into the larger description of the tag itself to be more descriptive.

I don't think it needs to be removed.  It just needs to be refined, which is what's happening.  We throw things at the wall and see what sticks.  Then refine and refine until there is consensus.  If there is no consensus we boot it.

**Comment by mattbasta** [comment]
@daveajones 

> I don't like custard, but I don't generally recommend removing it from all restaurants until a compelling need for it presents itself. Normally I try to understand what the hell people see in custard. I'm told some people quite like it.

I'm not suggesting removing it because I don't like it, I'm suggesting removing it from the spec being published in <30d until it can be given a strong story for how it would be used.

As-is, describing locations relevant to a show is simple on its face but ultimately lacks depth. If I tag all of my episodes with Chicago, because I'm in Chicago and talk about it a lot, that's perhaps useful for folks who are interested in hearing about Chicago. But if every single one of my episodes is tagged with Chicago, that doesn't help anyone looking for episodes about Chicago specifically (if every episode has only a few seconds of dialog about the city).

You can very much expect this to be abused: folks can (and will) tag their episodes with every location they can jam in to juice "the SEO" of their shows. This pollutes both the pool of location data to draw on and the consumer's ability to actually use that data for anything meaningful. At best, this offers a nice hook for apps and directories to implement a purely cosmetic feature showing the locations described by the show and its episodes. But without more structured data (a `rel` attribute?) it turns into a catch-all that you can't undo later without forcing everyone to revisit every location they've ever set for all of their episodes and add more metadata.

This is why I'm suggesting punting on this: talk to folks, do some research about what consumers' needs are, and update this to be rigorously thought out and hard to naively abuse. I'm genuinely trying to help you avoid a painful revert later on.
