### ISSUE TITLE
Consider removing method attribute from <podcast:contact>

### ISSUE THREAD

**Issue by mattbasta** [Podcastindex-org/podcast-namespace#74]
`<podcast:contact>` defines a `method` attribute, which overloads the behavior of the tag to support two different types of values: emails and URIs. However, support for email addresses is already well-supported with the `mailto:` scheme. The specification can be simplified by removing the `method` attribute and requiring app support for the `mailto:` scheme, which should trigger the consumer's email client.

Additionally, the specification should limit the URI schemes supported by the tag: `data:` and `file://` are likely security risks or could lead to unintended abuse of the spec.

**Comment by jamescridland** [comment]
This makes sense. Would you like to submit a pull request?

> The specification can be simplified by removing the method attribute and requiring app support for the mailto: scheme

I'm a fridge. I don't have support for an email client. But I can display an email address. That seems fair enough - no support for the `mailto:` scheme is required here other than displaying an email address.
