### ISSUE TITLE
<podcast:alternateEnclosure> differs from RSS spec

### ISSUE THREAD

**Issue by mattbasta** [Podcastindex-org/podcast-namespace#76]
`<podcast:alternateEnclosure>` specifies the `length` attribute to be "Duration of media asset in seconds". Per the RSS spec, `length` is defined as:

> length says how big it is in bytes

Consistency is important here: some podcast hosts have in the past (and currently) provided incorrect values for this attribute.

**Comment by daveajones** [comment]
Yep. Will fix. Thanks Matt.
