### ISSUE TITLE
<podcast:alternateEnclosure> should remove the bitrate attribute

### ISSUE THREAD

**Issue by mattbasta** [Podcastindex-org/podcast-namespace#78]
`<podcast:alternateEnclosure>` allows for a `bitrate` attribute. While this is interesting because it would allow a podcast app to download episodes of a reasonable quality for the current connection, it suffers from significant shortcomings:

- The bitrate of a file in many codecs isn't a useful apples-to-apples comparison between audio formats. An MP3 at 192kbps CBR is far larger than AAC at 128kbps, but both are (roughly) considered "transparent". Bitrate tells you little about what to expect within the file: the byte length would tell you far more.
- Not all encodings have a fixed bitrate (e.g., VBR audio)

In the "happy" case, the bitrate could be used to help inform the consumer about their choice of quality and data use. However, this requires the consumer to understand implementation details of the encoding of the content. The podcast app could try to make intelligent decisions, but the information provided—even when complete—offers little ability for a podcast app to make a meaningful choice based on the consumer's pre-specified intent.

Moreover, when the tags represent different types of content, the bitrate gives no data that's useful at download time.

I'd recommend removing the attribute unless there's a compelling use case for it.

**Comment by jamescridland** [comment]
> The bitrate of a file in many codecs isn't a useful apples-to-apples comparison between audio formats.

It isn't a useful comparison for "audio quality". However, it's a bloody useful way to learn which file is going to cost me more money to download, or which file I might actually be able to stream on my 56k6 modem. The latter is not (immediately) answered by the total bytesize.

A use-case might be that an app would download the high-bitrate version when on wifi, but the low-bitrate version when on mobile. However, if the content is different, I agree it would be helpful to know that. I wonder if there's a way to flag this?

> Not all encodings have a fixed bitrate (e.g., VBR audio)

VBR audio is not suitable for podcasting, and should not be used.

**Comment by daveajones** [comment]
What about avoiding the specific bitrate numbers altogether and instead using a nomenclature like “low”, “medium” or “high”.  That’s a pretty good indicator that the app can flag on to know what to grab if the connection is poor or great.

**Comment by tomrossi7** [comment]
> I might actually be able to stream on my 56k6 modem

Is it a US Robotics Dual Host? I loved mine!

> it's a bloody useful way to learn which file is going to cost me more money to download

Wouldn't the `length` of the enclosure be a better attribute to use in that case?

> What about avoiding the specific bitrate numbers altogether and instead using a nomenclature like “low”, “medium” or “high”.

Interesting! Do you think we need to support 3 different alternates? Would 2 work?

**Comment by jamescridland** [comment]
A long time ago, I was involved in a specification that had a "small", "medium" and "big" size for radio station logo. Built for the displays in use then, the sizes were 16x16, 32x32 and a staggering 64x64. I'm not much of a fan of those descriptions, having made that mistake.

For video, "low", "medium" and "high" may well suffer from the same problem.

In terms of making the feed - as a podcaster, I know I'm making a 128kbps file; I don't know that today's is 3,357,242 bytes long. The most complicated bit about rolling my own RSS feed has been working out durations and filesizes. I'd like to make things easy if possible.

But, if you feel that `length` is better, then that's fine. It occurs to me that the normal enclosure has that, and perhaps we should be aiming to mirror that.

**Comment by daveajones** [comment]
Needs more time to bake.  I always knew this would be one of the more complex tags to figure out.  I'm fine with booting this to phase 2 for now.  The world won't end.  :-)
