### ISSUE TITLE
<podcast:alternateEnclosure> should remove the stream attribute

### ISSUE THREAD

**Issue by mattbasta** [Podcastindex-org/podcast-namespace#79]
This attribute has a number of problems:

1. Boolean attributes in XML do not work like HTML. You cannot simply specify `stream`, you must specify something like `stream="stream"` (as with XHTML) or `stream="true"`.
2. This feels a lot like DRM, which is counter to the spirit of podcasting. If a device can start streaming content and play it, that content _can_ be saved and replayed. There is no technical reason that content cannot be saved: if you can open a socket and start playing audio, you can open a file handle and start playing those same bytes.
3. Without specifying a mechanism for negotiating a mechanism for "true" streaming (that is, adjusting bitrate to accommodate network conditions), the content is not "streaming", it's just a regular download.

**Comment by daveajones** [comment]
Agreed. That’s 99% of the time handled at the app later anyway.
