### ISSUE TITLE
<podcast:alternateEnclosure> may be present in an item when no enclosure is present

### ISSUE THREAD

**Issue by mattbasta** [Podcastindex-org/podcast-namespace#80]
`<podcast:alternateEnclosure>` does not require that `<enclosure>` is present within an `<item>` to be used. The RSS spec defines `<enclosure>` as an optional tag.

**Comment by daveajones** [comment]
Are you proposing that it _should_ require an `<enclosure>` to be present?  Or, that it should be clarified that one doesn't have to be?

**Comment by mattbasta** [comment]
@daveajones I'm suggesting that to have an `<podcast:alternateEnclosure>`, you must have an `<enclosure>`.
