### ISSUE TITLE
<podcast:images> should define image support

### ISSUE THREAD

**Issue by mattbasta** [Podcastindex-org/podcast-namespace#81]
The `<podcast:images>` tag does not specify any constraints for images. For compatibility, it should be strongly defined:

- Apps must support EXIF orientation
- Images must be in a well-supported format (e.g., JPG, PNG, WebP, etc.; inefficient formats like GIF should be banned)
- Images must not use an alpha channel
- Images must use RGB color space
- Images must be a reasonable DPI (Apple Podcasts requires 72 dpi)

These constraints will ensure compatibility between apps and hosting services, and avoid wasting bandwidth to download images that cannot be used.

**Comment by daveajones** [comment]
This feels like a definition that will absolutely be ignored.  Apple's own requirements aren't enforced around images.  They accept images that are in excess of what they specify.  We've seen 100+MB files, .PSD files, tiny images, etc.  It's all over the map.

To actually "ban" a format would require the hosting company to reject it upon upload for all of those reasons listed - many of which the user will not understand how to fix.  I'm ok with adding guidance here.  But, being too specific invites just ignoring the spec altogether.

**Comment by mattbasta** [comment]
@daveajones On the other hand, there's plenty of apps and directories that *will* fail if you don't have a compatible image. Pocket Casts is a popular notable (notorious?) example.

The spec should be prescriptive, such that tools like validators can enforce the rules. And when things don't work, nobody needs to fight over whose implementation is wrong: it's there in the spec. Specs are meant to say what the minimum bar is. Leaving that bar up to interpretation means chaos.

Allowing everything means everyone needs to support everything that could be supported, which isn't productive and results in fragmentation. The rules might be ignored, but then there is a concrete reason why things don't work.

**Comment by daveajones** [comment]
I'm not arguing what the point of specifications are.  I'm just asking how prepared hosts are to reject images for things like the RGB color space missing, and how they would explain that to their customer in a way that doesn't frustrate them when all they want to do is upload an image for their new episode.  "This image uses an alpha channel. Please remove it." is going to frustrate the hell out of a typical user.  They won't know what to do.

The namespace has to be realistic in what it tries to require. RFSM#11:  "If practice deviates from the spec, change the spec"

Requiring a "well-supported format" sounds very reasonable.  As well as not allowing GIF.  I think the deeper requirements like dpi, alpha, exif are going to be crazy hard to enforce.

**Comment by theDanielJLewis** [comment]
I think the hosting-providers could simply adjust the image as necessary.

For example, if it's transparent, flatten it on a white background. If it's CMYK or indexed, convert it to RGB (but this needs to be done in the right way so colors don't get crazy). If it's too tall or too wide, expand the other edges from their respective averaged color (for example, a wide gradient with white on the top and blue on the bottom would expand with those respective colors).

**Comment by mattbasta** [comment]
> I'm just asking how prepared hosts are to reject images for things like the RGB color space missing, and how they would explain that to their customer in a way that doesn't frustrate them when all they want to do is upload an image for their new episode. "This image uses an alpha channel. Please remove it." is going to frustrate the hell out of a typical user. They won't know what to do.

Pinecast already does this and provides an option to fix the image.

Artwork with alpha channels is extremely problematic today: many folks have art with a transparent background, which then gets displayed on a black (or white) background, making their image content disappear. It's impossible to know that your artwork will look very broken until well-after it's been uploaded and pushed out into the world, only to find that the alpha channel has been compositied onto black except for 0% opacity pixels, or that your artwork shows a black square on Spotify.

**Comment by jamescridland** [comment]
Most hosts either let you upload any old crap, or give you an error and don't fix it. I have given up pointing out how easy images are to get right, and how easy it is to fix images if they aren't (mainly), and now just assume that most hosts are happier dealing with the customer service headaches this creates rather than fix the issue.

However, this should be also read alongside the fact that most podcast publishers don't understand the basics about images - "how do I get this image under 500K?" is one such repeated comment in forums. For us to require EXIF or discuss DPIs isn't really a thing.

The wider question is whether someone will write a parser checker that proactively emails people (their hosts probably) with any issues. "Hey, we notice you're using a podcast:block statement in the wrong way". There's probably a business in that somehow.

**Comment by mattbasta** [comment]
Yes, the spec can be violated. Anything anyone writes can be violated. Saying

> For us to require EXIF or discuss DPIs isn't really a thing.

isn't productive for setting a standard, if you throw up your hands at actually setting the standard because someone will ignore you later. You could even argue that the folks who only care about handling customer support messages aren't going to bother integrating this spec in the first place, and the folks rolling their own solution aren't going to actually read the spec either. But, _putting it in the spec_ means that when Joe's Amazing Podcatcher doesn't support EXIF orientation—as many JPEG decoders do not—a validator somewhere will say "yeah the reason why your image is {90 degrees clockwise|the wrong colors|black on black} is that you didn't build the right thing: here's the details".

The spec _is designed for folks who do follow the rules_. You put the spec in place to set a north star for what a correct implementation looks like. If someone wants to properly support the orientation EXIF property? Awesome, please do. If someone wants to put 32-bit PNGs that they receive on a checkered background? Great. There's nothing wrong with that—that's not what this is about. The purpose of this proposal is to put up guardrails so that the minimum bar is established, and when things don't on a "good" implementation, it's clear and obvious why:

- Podcast hosts can consider these rules and normalize assets
- Podcast app developers can define meaningful minimum feature sets and constrain scope
- Validators can report issues _because they're already well-considered_
- Future versions of the spec can relax the constraints in a forwards and backwards-compatible way

**Comment by daveajones** [comment]
Spec design can easily become a flame war (the RSS battles of the 90’s we’re awful) and I don’t want that happening here. If you think those requirements should be defined in there, do a PR, I’ll merge it, and we’ll move on together and fry bigger fish. 😊
