### ISSUE TITLE
<podcast:newFeedUrl> should be removed

### ISSUE THREAD

**Issue by mattbasta** [Podcastindex-org/podcast-namespace#82]
The corresponding iTunes-specific tag is the source of much confusion and misuse. Its original purpose was to allow feed redirects for web server software that did not allow 301 redirects. Today, confusion exists that the tag should be used _on new feeds_ in lieu of a 301 redirect: this is patently incorrect (and silly, when you think about it...why would a feed tell you that it is the new URL for itself?). Today, this problem is essentially non-existent. Moreover, the similarity in naming to the `<itunes:new-feed-url>` tag may cause substantive confusion.

Overwhelmingly, however, a 301 redirect should be used to indicate that a feed has moved. When a 301 redirect is active, no HTTP response body should be sent, only HTTP headers. In that situation, a `<podcast:newFeedUrl>` _could not_ be sent to an app or directory, since the server never sends any XML back.

Since this tag really has no compelling use beyond a very old (proprietary) historical use case which isn't well-known or well-supported anyway, it should be removed.

**Comment by jamescridland** [comment]
This seems sensible.

**Comment by daveajones** [comment]
I agree with that too. The solution is 3xx redirects. Keeping it out of the feed altogether is good. Will remove.

**Comment by theDanielJLewis** [comment]
> Today, confusion exists that the tag should be used _on new feeds_ in lieu of a 301 redirect: this is patently incorrect (and silly, when you think about it...why would a feed tell you that it is the new URL for itself?).

I'm sorry, but _that_ is incorrect. 

There should be a redirect from the old feed and the new feed should contain `<itunes:new-feed-url>` pointing at itself, which "locks in" the change with Apple Podcasts and speeds up the catalog update.

[From Apple](https://help.apple.com/itc/podcasts_connect/#/itc4fb390137):

> **If you host your own RSS feed**
> If you don’t use a third-party podcast hosting solution and you directly edit or maintain the original RSS feed, follow the steps below. This will ensure that your existing subscribers (even those outside of Apple Podcasts) are seamlessly migrated and are not affected by this process:
> 
> 1. Set the web server where your feed is hosted to return an HTTP 301 redirect response when it receives a request for the old feed.
> 2. Use the <itunes:new-feed-url> tag in your new feed to point to the new URL. This response updates Apple Podcasts with the new feed URL and your subscribers continue to receive new episodes automatically.

`<itunes:new-feed-url>` should be used on old feeds only when a redirect is not possible, such as with Podomatic and some other hosting providers. But even then, the tag is not supported and honored by all podcast apps.

All this said, yes, 301 redirects are still the best way. So with so little support for the Apple tag, I agree that we shouldn't complicate things further with replicating that to our spec.

**Comment by mattbasta** [comment]
@theDanielJLewis This is the biggest hill I'll die on 😂 

Apple's older pre-2017 RSS spec (I cannot find the PDF but I am furiously searching my computer) included a small ambiguity, which I believe has been carried forward in a bad game of telephone ever since—notably on their support website. It makes no sense for a feed to describe its own location as a means for updating a feed's location: if I clone Marc Maron's podcast, put the `<itunes:new-feed-url>` tag in it pointing at my cloned feed, and submit it to Apple, it shouldn't replace WTF. If this _actually_ worked the way it is described, anyone could simply steal anyone else's feed.

I've done experiments (not directly related to this—they were related to users who wanted to rename their feeds) and found that a single iTMS bot on the Apple ASN requesting a 301-ed feed ceases all accesses to the old feed and always requests the new feed. So I'm not sure how updates to their catalog could be made any faster.

If you flip "in your new feed" to "in your old feed" (or remove "new" entirely) in the most recent copy on the support website, the tag makes much more sense, solving an actual problem that users have had and which would have been substantially more prominent fifteen years ago. What I believe the tag is supposed to be used for essentially shifts the redirect from the HTTP headers to the HTTP response body, which is a very sensible consideration for folks who don't have control over their HTTP headers.

This is honestly one of the most frustrating docs bugs I've ever encountered, because it's led to thousands of people cargo-culting a behavior which isn't useful to them. A single one word typo (or what I believe to be a typo) has wasted many thousands—if not tens of thousands—of hours of people's time.

**Comment by theDanielJLewis** [comment]
I know it doesn't make sense. It's like how midwesterners use their turn signals: to indicate that they _have_ changed lanes.

But that redirect to new-feed-url process _is_ how Apple Podcasts has worked for a few years.

> … if I clone Marc Maron's podcast, put the <itunes:new-feed-url> tag in it pointing at my cloned feed, and submit it to Apple, it shouldn't replace WTF. If this actually worked the way it is described, anyone could simply steal anyone else's feed.

Right. It won't because you're neither 301-redirecting the old feed nor putting `<itunes:new-feed-url>` in the old feed. All you would be doing is confirming "this feed is the correct feed." And without control over the old feed, you would not be able to take over his show in Apple Podcasts. Besides, the scenario you're describing is not how Apple explained the tag.

> I've done experiments (not directly related to this—they were related to users who wanted to rename their feeds) and found that a single iTMS bot on the Apple ASN requesting a 301-ed feed ceases all accesses to the old feed and always requests the new feed. So I'm not sure how updates to their catalog could be made any faster.

Redirects are immediate, yes. And it sounds like that's what you tested. But Apple continued to have the catalog ID pointing to the old feed until it eventually updated the catalog data based on the redirect. An Apple Media Lookup would have shown the old feed URL on that catalog ID. But using `<itunes:new-feed-url>` would make the _catalog_ update faster.

Apple is notorious for describing things in only ideals, not all possible scenarios.

Regardless, I agree with you that replicating anything like this in the Podcast namespace would be unnecessary.
