### ISSUE TITLE
"Verification for Importing and Transferring" should be updated to account for verified emails

### ISSUE THREAD

**Issue by mattbasta** [Podcastindex-org/podcast-namespace#83]
The wording should be updated to account for hosting services that verify their users' emails already. If the email matches the one in the feed, it should be safe to import the podcast.

**Comment by tomrossi7** [comment]
So are you saying the `locked` status could be disregarded if the host has already verified the users email address ?

**Comment by daveajones** [comment]
Do you mean that if the owner=“” attribute is blank then it should be assumed that some other email address in the feed is validated?  Trying to make sure I understand you.

**Comment by mattbasta** [comment]
@tomrossi7 is correct. Though it seems like it would be a real hassle if `owner` was blank. There's no actionable message to send the user. "You can't import this show, go talk to your old host to get it unlocked". Why not make `owner` required?

Being real, I'll probably ignore the tag if the owner attribute is blank. It's going to be trivial for someone to write a FeedBurner-esque proxy that just serves up feeds without the locked tag. I might build it myself as a tool for my customers who are stuck—a situation like this will likely require it.

**Comment by daveajones** [comment]
Ah, I see your meaning now.  I'll add some wording around that.

BTW, thanks for getting involved here Matt.  Your run through yesterday with catching wording stuff and suggestions were very helpful.
