### ISSUE TITLE
Criteria for Tag Adoption

### ISSUE THREAD

**Issue by tomrossi7** [Podcastindex-org/podcast-namespace#85]
What do you all think about creating criteria for tag adoption? For example, what if we said **a tag is not accepted into the namespace until it is committed/supported by at least one podcast hosting company and one podcast player**? This may help us focus on the new tags that are most important?

**Comment by daveajones** [comment]
Yes, there needs to be a better, clearer explanation of the adoption process. It’s my fault for leaving some of that unsaid.

I mean to do that on Friday’s show.  But, I’ll write something up here as a starting point that can be refined.

**Comment by tomrossi7** [comment]
This may make it easier for your original timeline proposal. Rather than having a date when multiple tags all will be adopted, we could just say tags are adopted as they put into practice by the industry 🤷‍♂️

**Comment by daveajones** [comment]
My wording was confusing.  I stated that "whatever tags are still in phase 1 at that point will be officially formalized."  What was left unsaid was that I don't expect there to be much left in phase 1 to adopt.  The phase 1 closing date was just meant to let us go ahead and get a few important tags defined and out in the wild.  The ones that had been discussed for years, or were already in practice "like transcripts".  The rest of the phase 1 stuff was just proposals/ideas that I've always expected to be pushed back.  Things like "newFeedUrl" and "images" are meant as discussion points to see if any agreement forms around them.

**Comment by daveajones** [comment]
Added more clarity here:  https://github.com/Podcastindex-org/podcast-namespace#current-roadmap

**Comment by theDanielJLewis** [comment]
I think we should refer to version numbers, instead of phases. That can be a lot more easily iterative, too. 1.1 could simply add a couple formalized tags, but "phase 2" sounds like it has to be a lot bigger.

**Comment by daveajones** [comment]
That wouldn't work because there may be some periods of work where nothing actually gets formalized.  We'll figure it out and make a change to the process as we go if we see this way is cumbersome.  No biggie.
