### ISSUE TITLE
Chapters: merge with ChaptersApp JSON

### ISSUE THREAD

**Issue by daveajones** [Podcastindex-org/podcast-namespace#91]
Let's work with @bjoreman to integrate the ChaptersApp JSON format.  Maybe a good place to start would be to figure out what to do with "startTime" vs "startMs".

**Comment by bjoreman** [comment]
Posted over on #55 before I noticed this issue existing:

I'm all for adjusting the format used to what we arrive at here.
For context, my thinking for the property name and unit is that it minimizes the risk of misunderstanding (not least by myself) to have the unit used right in the name, and it feels good to have a unit not in need of the fraction side of the world. Floats always seem to bite me, sooner or later :-) …

**Comment by bjoreman** [comment]
includeInTableOfContents, if we decide to include that, is definitely open for renaming as well :-) …
The name pretty much only makes sense from the viewpoint of the ID3 chapter standard's internals, and I mostly picked it because it makes the true/false state match what's written inside the ID3 tag.

**Comment by daveajones** [comment]
I'm going to write up a rough draft to give us something to hack on.

**Comment by tomrossi7** [comment]
Internally dealing with floats is painful, but providing an integer for ms gets verbose fast. We just dealt with this in transcripts as well. I would suggest startSeconds. This allows the value to be 35 vs 35000 but still leaves freedom for 25.123 vs 25123 for chapter markers that are captured in ms. I don't feel *that* strongly, but wanted to put this out there. Keep in mind that we already use seconds for duration as well as timestamps for transcripts.

**Comment by daveajones** [comment]
This is good info Tom. 

@bjoreman, do you have a problem with this change?

"startMs" (milliseconds) being changed to "startSeconds" (float) containing the time as seconds if just a whole number, or milliseconds if given as a decimal.

**Comment by bjoreman** [comment]
I don’t have a very strong opinion either, if there are other places seconds are already used I guess it makes sense.

**Comment by daveajones** [comment]
Ok, I kept `startTime` as the name since it already matches what's in transcripts.  Look at the new draft document [here](/chapters/jsonChapters.md) and let me know what yall think.

@bjoreman I think the way it's written it would be three changes on your side:  the time format/name, changing the table of contents property name to `toc` and changing `hasArtwork` to be the name of the file rather than a boolean, to allow for it to be used even if no chapter id string is present.

On our side, we can now use the relative artwork links for more complexity if wanted.

**Comment by MartinMouritzen** [comment]
Please, let's move away from `title` being required! 

That would 
1) enable showing multiple images within the same chapter.
2) Mean we have no use for the `toc`, since not providing a title would mean you do not want it in the ToC.

also if `id` is optional, I am not sure I see the great value in it?

**Comment by bjoreman** [comment]
Not requiring a title makes sense to me, but I think that should be separate from denoting if we want the chapter hidden/in the ToC or not. In part because it’s nice to be explicit, but mainly because this is supported by the ID3 chapters standard and thus presently handled by chapter-supporting podcast apps.

**Comment by bjoreman** [comment]
Sounds sensible to me.

Unless there are additional reasons to keep it, I think I’m in favor of dropping hasArtwork altogether. It was the most convenient way of doing things for Podcast Chapter’s particular use case, but if that’s the only motivation I don’t think that should be preserved in a standard.

**Comment by daveajones** [comment]
Are you thinking you would just use "img" instead and write the image name as a relative url?

**Comment by bjoreman** [comment]
That was my thought, yes. But perhaps that won’t improve anything? I freely admit to still being a bit stuck in the viewpoint of my app’s original use case 🤔☺️.

**Comment by daveajones** [comment]
It does make sense that way.  If the `img` is `ch1.img` it should work fine in the embedded player.  And if it's a FQDN it would work externally too.  Seems to simplify things.  And, hasArtwork is implicit in having the `img` there or not. 

Ok, about to post a new version for review.

**Comment by daveajones** [comment]
`title` also optional now.  But encouraged for clarity.

**Comment by daveajones** [comment]
@tomrossi7 Is this looking like something that would be workable for you guys?  Want to make sure it won't break what you're working on.  I don't think it will from what I see.

**Comment by tomrossi7** [comment]
I don't see any technical issues with this. What do you think @snookfin?

**Comment by snookfin** [comment]
Good suggestions all around. I think this will work nicely.

**Comment by daveajones** [comment]
@bjoreman Are you good with this as a version 1.1 format for the initial release?  I think the code change you'll have to make should be fairly minor.

**Comment by bjoreman** [comment]
Yes, sounds good to me!

Vänliga hälsningar,
Fredrik Björeman

**Comment by daveajones** [comment]
Success:  https://apps.apple.com/us/app/podcast-chapters/id1070963477?mt=12&ign-mpt=uo%3D4

Thanks @bjoreman !!
