### ISSUE TITLE
<podcast:alternateEnclosure - some form of programmatic understanding of content is needed

### ISSUE THREAD

**Issue by jamescridland** [Podcastindex-org/podcast-namespace#94]
Chatting with someone about how this might work, and came upon an interesting issue.

You could use `<podcast:alternateEnclosure` to offer different encodings of the same audio. (All these work, by the way):

``` 
<podcast:alternateEnclosure title="Opus" url="https://podnews.net/audio/podnews201029.opus" type="audio/opus" length="809242"/>
<podcast:alternateEnclosure title="MP3" url="https://podnews.net/audio/podnews201029.mp3" type="audio/mpeg" length="3214986" />
<podcast:alternateEnclosure title="AAC" url="https://podnews.net/audio/podnews201029.m4a" type="audio/x-m4a" length="1191082" />
```

You could also use it to offer a "director's cut" - the full interview, for example, or a social media snippet.

``` 
<podcast:alternateEnclosure title="Complete interview" url="https://example.com/complete.mp3" type="audio/mp3" length="3214986"/>
<podcast:alternateEnclosure title="Shareable snippet" url="https://example.com/snippet.mp3" type="audio/mp3" length="232323"/>
``` 

* How would a podcast app know which of the above were **the same audio** but just different encodings?
* How would a podcast app write something that offers a data-saving option - "download the smallest version when on cellular data"?
* How would a podcast app be able to dynamically switch between a high and low bitrate version?

Is it worth considering a `rel="alternate"` or `rel="additional"` type descriptor to indicate this?

**Comment by daveajones** [comment]
That's a good idea.  Having it there could allow for expanding this tag's usage easily, even if it's not immediate.  Will add.
